MACVETH: macveth::MVCPUInfo Class Reference
macveth::MVCPUInfo Class Reference
#include "/home/markoshorro/workspace/MACVETH/include/CPUID.h"
Public Types
enum MVISA {
AUTODETECT = -1, SSE = 10, AVX = 20, AVX2 = 21,
AVX512 = 22
}
Supported ISA.
enum MVArch {
NATIVE, DEFAULT, Nehalem, Westmere,
SandyBridge, IvyBridge, Haswell, Broadwell,
Skylake, KabyLake, CoffeeLake, CascadeLake,
IceLake, Zen, Zen2, AMDDef,
IntelDef
}
Supported architectures.
Public Member Functions
MVCPUInfo ()
MVArch getArchitectureFromCPUID (CPUID C)
TODO: Get architecture name from values in EAX.
MVArch getArchitecture ()
Get architecture name.
std::string vendor () const
Get vendor name.
std::string model () const
Get model name.
int cores () const
Get number of cores.
float cpuSpeedInMHz () const
Get speed in MHz.
bool isSSE () const
bool isSSE2 () const
bool isSSE3 () const
bool isSSE41 () const
bool isSSE42 () const
bool isAVX () const
bool isAVX2 () const
bool isAVX512F () const
bool isAVX512CD () const
bool isAVX512ER () const
bool isAVX512PF () const
bool isHyperThreaded () const
int logicalCpus () const
Detailed Description
Definition at line 71 of file CPUID.h.
Member Enumeration Documentation
MVArch
enum macveth::MVCPUInfo::MVArch
Supported architectures.
This enum is util for computing the cost model, as different architectures may differ in the latencies and thoughputs of operations for the same ISA
Enumerator
NATIVE
TODO: Autodetect the architecture underlying.
DEFAULT
Default or not specified.
Nehalem
1st-gen Intel Nehalem (2009) architecture (tock): SSE4.2
Westmere
1st-gen (and 2) Intel Westmere (2010) architecture (tick): SSE4.2
SandyBridge
2nd-gen Intel Sandy Bridge (2011) architecture (tock): AVX
IvyBridge
3rd-gen Intel Ivy Bridge (2012) architecture (tick): AVX
Haswell
4th-gen Intel Haswell (2013) architecture (tock): AVX2
Broadwell
5th-gen Intel Broadwell (2014) architecture (tick): AVX2
Skylake
6th-gen Intel Skylake (2015) architecture (tock): AVX2, AVX512 (Skylake-SP)
KabyLake
7th-gen Intel Kaby Lake (2016) architecture: AVX2
CoffeeLake
8-9th-gen Intel Coffee Lake (2017) architecture: AVX2
CascadeLake
8th-gen (server) Intel Cascade Lake (2019) architecture: AVX512
IceLake
10th-gen Intel Cascade Lake (2019) architecture: AVX512
Zen
AMD Zen architecture: AVX2.
Zen2
AMD Zen2 architecture: AVX2.
AMDDef
AMD default.
IntelDef
Intel Default.
Definition at line 90 of file CPUID.h.
MVISA
enum macveth::MVCPUInfo::MVISA
Supported ISA.
Enumerator
AUTODETECT
TODO: detect ISA.
SSE
SSE support.
AVX
AVX support.
AVX2
AVX2 support.
AVX512
AVX512 support.
Definition at line 74 of file CPUID.h.
Constructor & Destructor Documentation
MVCPUInfo()
macveth::MVCPUInfo::MVCPUInfo () inline
Definition at line 128 of file CPUID.h.
References macveth::CPUID::EAX(), macveth::CPUID::EBX(), macveth::CPUID::ECX(), macveth::CPUID::EDX(), getArchitectureFromCPUID(), and MAX_INTEL_TOP_LVL.
Member Function Documentation
cores()
int macveth::MVCPUInfo::cores () const inline
Get number of cores.
Definition at line 242 of file CPUID.h.
cpuSpeedInMHz()
float macveth::MVCPUInfo::cpuSpeedInMHz () const inline
Get speed in MHz.
Definition at line 244 of file CPUID.h.
getArchitecture()
MVArch macveth::MVCPUInfo::getArchitecture () inline
Get architecture name.
Definition at line 236 of file CPUID.h.
Referenced by macveth::MVOptions::getMVArch().
getArchitectureFromCPUID()
MVArch macveth::MVCPUInfo::getArchitectureFromCPUID (CPUID C) inline
TODO: Get architecture name from values in EAX.
Definition at line 234 of file CPUID.h.
Referenced by MVCPUInfo().
isAVX()
bool macveth::MVCPUInfo::isAVX () const inline
Definition at line 250 of file CPUID.h.
Referenced by macveth::MVOptions::getMVISA().
isAVX2()
bool macveth::MVCPUInfo::isAVX2 () const inline
Definition at line 251 of file CPUID.h.
Referenced by macveth::MVOptions::getMVISA().
isAVX512CD()
bool macveth::MVCPUInfo::isAVX512CD () const inline
Definition at line 253 of file CPUID.h.
isAVX512ER()
bool macveth::MVCPUInfo::isAVX512ER () const inline
Definition at line 254 of file CPUID.h.
isAVX512F()
bool macveth::MVCPUInfo::isAVX512F () const inline
Definition at line 252 of file CPUID.h.
Referenced by macveth::MVOptions::getMVISA().
isAVX512PF()
bool macveth::MVCPUInfo::isAVX512PF () const inline
Definition at line 255 of file CPUID.h.
isHyperThreaded()
bool macveth::MVCPUInfo::isHyperThreaded () const inline
Definition at line 256 of file CPUID.h.
isSSE()
bool macveth::MVCPUInfo::isSSE () const inline
Definition at line 245 of file CPUID.h.
isSSE2()
bool macveth::MVCPUInfo::isSSE2 () const inline
Definition at line 246 of file CPUID.h.
isSSE3()
bool macveth::MVCPUInfo::isSSE3 () const inline
Definition at line 247 of file CPUID.h.
isSSE41()
bool macveth::MVCPUInfo::isSSE41 () const inline
Definition at line 248 of file CPUID.h.
isSSE42()
bool macveth::MVCPUInfo::isSSE42 () const inline
Definition at line 249 of file CPUID.h.
Referenced by macveth::MVOptions::getMVISA().
logicalCpus()
int macveth::MVCPUInfo::logicalCpus () const inline
Definition at line 257 of file CPUID.h.
model()
std::string macveth::MVCPUInfo::model () const inline
Get model name.
Definition at line 240 of file CPUID.h.
vendor()
std::string macveth::MVCPUInfo::vendor () const inline
Get vendor name.
Definition at line 238 of file CPUID.h.
The documentation for this class was generated from the following file:
MACVETH/include/CPUID.h