MACVETH: macveth::Utils Class Reference
macveth::Utils Class Reference
#include "/home/markoshorro/workspace/MACVETH/include/Utils.h"
Public Types
using StrList = std::list< std::string >
Type of string list.
Static Public Member Functions
template<typename T >
static bool contains (std::list< T > listOfElements, T element)
Check if list contains an element given.
static std::string getStringFromStmt (const Stmt *S)
Converting clang expressions to strings.
static std::string getStringFromExpr (const Expr *E)
Converting clang expressions to strings.
static int64_t getIntFromExpr (const Expr *E)
Given an Expr, get its integer value.
static bool isNumericValue (Expr *E)
Check whether expression is or not numeric.
static std::string toUppercase (std::string S)
String to uppercase.
static void initFile (std::string FileName)
Truncate file: create or rewrite if already created.
static clang::SourceManager * getSourceMgr ()
Get clang SourceManager.
static clang::LangOptions * getLangOpts ()
Get clang LangOptions.
static clang::ASTContext * getCtx ()
Get clang ASTContext.
static void setOpts (SourceManager *SO, LangOptions *LO, ASTContext *C)
Set some clang resources.
static std::string getExePath ()
Get execution path of the binary; not just a getcwd() call.
Static Public Attributes
static clang::SourceManager * SourceMgr
When declaring static members of class, when assigning them you need to redeclare them or since C++17 you can just put in.
static clang::LangOptions * LangOpts
static clang::ASTContext * Ctx
Detailed Description
Definition at line 48 of file Utils.h.
Member Typedef Documentation
StrList
using macveth::Utils::StrList = std::list<std::string>
Type of string list.
Definition at line 51 of file Utils.h.
Member Function Documentation
contains()
template<typename T > static bool macveth::Utils::contains (std::list< T > listOfElements, T element) static
Check if list contains an element given.
getCtx()
static clang::ASTContext* macveth::Utils::getCtx () static
Get clang ASTContext.
getExePath()
static std::string macveth::Utils::getExePath () static
Get execution path of the binary; not just a getcwd() call.
getIntFromExpr()
static int64_t macveth::Utils::getIntFromExpr (const Expr * E) static
Given an Expr, get its integer value.
Referenced by macveth::MVExprArray::MVAffineIndex::MVAffineIndex().
getLangOpts()
static clang::LangOptions* macveth::Utils::getLangOpts () static
Get clang LangOptions.
getSourceMgr()
static clang::SourceManager* macveth::Utils::getSourceMgr () static
Get clang SourceManager.
getStringFromExpr()
static std::string macveth::Utils::getStringFromExpr (const Expr * E) static
Converting clang expressions to strings.
Referenced by macveth::MVExprArray::MVAffineIndex::MVAffineIndex(), macveth::MVExprArray::MVExprArray(), and macveth::MVExprLiteral::toString().
getStringFromStmt()
static std::string macveth::Utils::getStringFromStmt (const Stmt * S) static
Converting clang expressions to strings.
initFile()
static void macveth::Utils::initFile (std::string FileName) inline static
Truncate file: create or rewrite if already created.
Definition at line 84 of file Utils.h.
isNumericValue()
static bool macveth::Utils::isNumericValue (Expr * E) static
Check whether expression is or not numeric.
setOpts()
static void macveth::Utils::setOpts (SourceManager * SO, LangOptions * LO, ASTContext * C) static
Set some clang resources.
toUppercase()
static std::string macveth::Utils::toUppercase (std::string S) inline static
String to uppercase.
Definition at line 77 of file Utils.h.
Referenced by macveth::MVOp::getTableMVOPstr().
Member Data Documentation
Ctx
clang::ASTContext* macveth::Utils::Ctx inline static
Definition at line 58 of file Utils.h.
LangOpts
clang::LangOptions* macveth::Utils::LangOpts inline static
Definition at line 57 of file Utils.h.
SourceMgr
clang::SourceManager* macveth::Utils::SourceMgr inline static
When declaring static members of class, when assigning them you need to redeclare them or since C++17 you can just put in.
Definition at line 56 of file Utils.h.
The documentation for this class was generated from the following file:
MACVETH/include/Utils.h