MACVETH: macveth::SIMDBackEndFactory Class Reference
macveth::SIMDBackEndFactory Class Reference
Wrapper for avoiding low level details when creating the different backends.
#include "/home/markoshorro/workspace/MACVETH/include/Vectorization/SIMD/SIMDBackEndFactory.h"
Static Public Member Functions
static SIMDBackEnd * getBackend (MVCPUInfo::MVISA ISA)
Return a specific backend given as input.
Detailed Description
Wrapper for avoiding low level details when creating the different backends.
Definition at line 38 of file SIMDBackEndFactory.h.
Member Function Documentation
getBackend()
static SIMDBackEnd* macveth::SIMDBackEndFactory::getBackend (MVCPUInfo::MVISA ISA) inline static
Return a specific backend given as input.
TODO: only AVX2 implemented yet...
Definition at line 41 of file SIMDBackEndFactory.h.
References macveth::AVX2BackEnd::getSingleton(), ISA(), and macveth::MVErr().
The documentation for this class was generated from the following file:
MACVETH/include/Vectorization/SIMD/SIMDBackEndFactory.h