MACVETH: macveth::StmtWrapper Class Reference
macveth::StmtWrapper Class Reference
StmtWrapper, as its name suggests, wraps statements, its TAC representation and the desired intrinsic translation.
#include "/home/markoshorro/workspace/MACVETH/include/StmtWrapper.h"
Classes
struct LoopInfo
Helper structure to handle the loop information for this statement.
Public Types
using LoopList = std::list< LoopInfo >
LoopInfo list type.
Public Member Functions
~StmtWrapper ()
Default destructor.
StmtWrapper ()
Empty constructor.
StmtWrapper (clang::Stmt *S)
Main constructor, based on clang's Stmt.
TacListType unroll (LoopInfo L)
Perform unrolling for a given statement given its unroll factor and the upperbound of the loop.
bool unrollAndJam (std::list< LoopInfo > LI, ScopLoc *Scop)
Unrolls the TAC list in all the possible dimensions.
bool unrollByDim (std::list< LoopInfo > LI, ScopLoc *Scop)
Unrolls the TAC list in the specified dimensions.
bool unrollLoopList (std::list< LoopInfo > LI)
Unroll a list of given loops and return if full unrolling was performed.
std::list< StmtWrapper * > getListStmt ()
Get list of statements.
LoopInfo getLoopInfo ()
Get LoopInfo structure.
Stmt * getClangStmt ()
Get Clang Stmt.
TacListType getTacList ()
Get TAC list.
void setTacList (TacListType TacList)
Set TAC list in the StmtWrapper.
bool isLoop ()
StmtWrapper may me a "regular" statement or a for loop.
bool isLeftOver ()
Check if StmtWrapper holds a leftover (i.e. does not hold a loop)
void setInnerLoopInfo (LoopInfo InnerLoopInfo)
Set the name of the loop surrounding this Stmt.
std::string getInnerLoopName ()
Get the name of the loop surrounding this clang::Stmt.
bool isInLoop ()
void setNotVectorized ()
bool isVectorized ()
long getScop ()
Static Public Member Functions
static std::list< StmtWrapper * > genStmtWraps (CompoundStmt *CS, ScopLoc *Scop)
Generate a list of StmtWrapper.
static LoopInfo getLoop (clang::ForStmt *ForLoop)
Get all the loops given one.
Static Public Attributes
static constexpr int UBFallback = 4
Default value.
Detailed Description
StmtWrapper, as its name suggests, wraps statements, its TAC representation and the desired intrinsic translation.
Definition at line 45 of file StmtWrapper.h.
Member Typedef Documentation
LoopList
using macveth::StmtWrapper::LoopList = std::list<LoopInfo>
LoopInfo list type.
Definition at line 119 of file StmtWrapper.h.
Constructor & Destructor Documentation
~StmtWrapper()
macveth::StmtWrapper::~StmtWrapper () inline
Default destructor.
Definition at line 128 of file StmtWrapper.h.
StmtWrapper() [1/2]
macveth::StmtWrapper::StmtWrapper () inline
Empty constructor.
Definition at line 131 of file StmtWrapper.h.
StmtWrapper() [2/2]
macveth::StmtWrapper::StmtWrapper (clang::Stmt * S)
Main constructor, based on clang's Stmt.
Member Function Documentation
genStmtWraps()
static std::list<StmtWrapper *> macveth::StmtWrapper::genStmtWraps (CompoundStmt * CS, ScopLoc * Scop) static
Generate a list of StmtWrapper.
getClangStmt()
Stmt* macveth::StmtWrapper::getClangStmt () inline
Get Clang Stmt.
Definition at line 156 of file StmtWrapper.h.
getInnerLoopName()
std::string macveth::StmtWrapper::getInnerLoopName () inline
Get the name of the loop surrounding this clang::Stmt.
Definition at line 184 of file StmtWrapper.h.
References macveth::StmtWrapper::LoopInfo::getDim().
getListStmt()
std::list<StmtWrapper *> macveth::StmtWrapper::getListStmt () inline
Get list of statements.
Definition at line 150 of file StmtWrapper.h.
getLoop()
static LoopInfo macveth::StmtWrapper::getLoop (clang::ForStmt * ForLoop) static
Get all the loops given one.
getLoopInfo()
LoopInfo macveth::StmtWrapper::getLoopInfo () inline
Get LoopInfo structure.
Definition at line 153 of file StmtWrapper.h.
getScop()
long macveth::StmtWrapper::getScop () inline
Definition at line 192 of file StmtWrapper.h.
getTacList()
TacListType macveth::StmtWrapper::getTacList () inline
Get TAC list.
Definition at line 159 of file StmtWrapper.h.
Referenced by setInnerLoopInfo().
isInLoop()
bool macveth::StmtWrapper::isInLoop () inline
Definition at line 186 of file StmtWrapper.h.
References macveth::StmtWrapper::LoopInfo::getDim().
isLeftOver()
bool macveth::StmtWrapper::isLeftOver () inline
Check if StmtWrapper holds a leftover (i.e. does not hold a loop)
Definition at line 169 of file StmtWrapper.h.
References isLoop().
isLoop()
bool macveth::StmtWrapper::isLoop () inline
StmtWrapper may me a "regular" statement or a for loop.
This is useful for identifying properly regions
Definition at line 166 of file StmtWrapper.h.
Referenced by isLeftOver().
isVectorized()
bool macveth::StmtWrapper::isVectorized () inline
Definition at line 190 of file StmtWrapper.h.
setInnerLoopInfo()
void macveth::StmtWrapper::setInnerLoopInfo (LoopInfo InnerLoopInfo) inline
Set the name of the loop surrounding this Stmt.
Definition at line 172 of file StmtWrapper.h.
References macveth::StmtWrapper::LoopInfo::getDim(), getTacList(), and setTacList().
setNotVectorized()
void macveth::StmtWrapper::setNotVectorized () inline
Definition at line 188 of file StmtWrapper.h.
setTacList()
void macveth::StmtWrapper::setTacList (TacListType TacList) inline
Set TAC list in the StmtWrapper.
Definition at line 162 of file StmtWrapper.h.
Referenced by setInnerLoopInfo().
unroll()
TacListType macveth::StmtWrapper::unroll (LoopInfo L)
Perform unrolling for a given statement given its unroll factor and the upperbound of the loop.
unrollAndJam()
bool macveth::StmtWrapper::unrollAndJam (std::list< LoopInfo > LI, ScopLoc * Scop)
Unrolls the TAC list in all the possible dimensions.
unrollByDim()
bool macveth::StmtWrapper::unrollByDim (std::list< LoopInfo > LI, ScopLoc * Scop)
Unrolls the TAC list in the specified dimensions.
unrollLoopList()
bool macveth::StmtWrapper::unrollLoopList (std::list< LoopInfo > LI)
Unroll a list of given loops and return if full unrolling was performed.
Member Data Documentation
UBFallback
constexpr int macveth::StmtWrapper::UBFallback = 4 static constexpr
Default value.
Definition at line 48 of file StmtWrapper.h.
The documentation for this class was generated from the following file:
MACVETH/include/StmtWrapper.h