MACVETH: macveth::MVExprArray::MVAffineIndex Struct Reference
macveth::MVExprArray::MVAffineIndex Struct Reference
Abstraction to handle affine indices in MACVETH.
#include "/home/markoshorro/workspace/MACVETH/include/MVExpr/MVExprArray.h"
Public Member Functions
bool isTerminal ()
Check if index is terminal or not (has real Val)
MVAffineIndex ()
Empty constructor.
MVAffineIndex (MVAffineIndex *M)
Create a copy of an MVAffineIndex.
void setVal (std::string Val)
If we set a Val, then there it has no leaves.
void deleteLhs ()
Delete safely the LHS of the expression.
void deleteRhs ()
Delete safely the RHS of the expression.
void simplifyIndex ()
Simplify expression in order to better calculate indices and so.
MVAffineIndex (const Expr *E)
Main constructor.
MVAffineIndex (std::string S)
Constructor when given only a string.
bool updateIndex (int UF, std::string LL, bool SubstituteVal)
Update index recursively.
int operator- (const MVAffineIndex &M)
std::string toString ()
Convert to string recursively.
Static Public Member Functions
static MVAffineIndex copy (MVAffineIndex O)
Copy constructor.
Public Attributes
MVAffineIndex * LHS = nullptr
Left part of the expression, if it has.
MVAffineIndex * RHS = nullptr
Right part of the expression, if it has.
std::string Val = ""
FIXME: Value of the expression (we do not care of its type, we handle strings)
std::map< std::string, bool > Unrolled
Unrolled.
clang::BinaryOperator::Opcode OP
BinaryOperator of the expression if it has any.
Detailed Description
Abstraction to handle affine indices in MACVETH.
Definition at line 41 of file MVExprArray.h.
Constructor & Destructor Documentation
MVAffineIndex() [1/4]
macveth::MVExprArray::MVAffineIndex::MVAffineIndex () inline
Empty constructor.
Definition at line 77 of file MVExprArray.h.
Referenced by copy(), MVAffineIndex(), and updateIndex().
MVAffineIndex() [2/4]
macveth::MVExprArray::MVAffineIndex::MVAffineIndex (MVAffineIndex * M) inline
Create a copy of an MVAffineIndex.
Definition at line 80 of file MVExprArray.h.
References LHS, MVAffineIndex(), OP, RHS, Unrolled, and Val.
MVAffineIndex() [3/4]
macveth::MVExprArray::MVAffineIndex::MVAffineIndex (const Expr * E) inline
Main constructor.
Definition at line 205 of file MVExprArray.h.
References macveth::Utils::getIntFromExpr(), macveth::Utils::getStringFromExpr(), MVAffineIndex(), and simplifyIndex().
MVAffineIndex() [4/4]
macveth::MVExprArray::MVAffineIndex::MVAffineIndex (std::string S) inline
Constructor when given only a string.
Definition at line 253 of file MVExprArray.h.
Member Function Documentation
copy()
static MVAffineIndex macveth::MVExprArray::MVAffineIndex::copy (MVAffineIndex O) inline static
Copy constructor.
Definition at line 60 of file MVExprArray.h.
References LHS, MVAffineIndex(), OP, RHS, Unrolled, and Val.
Referenced by macveth::MVExprArray::MVExprArray().
deleteLhs()
void macveth::MVExprArray::MVAffineIndex::deleteLhs () inline
Delete safely the LHS of the expression.
Definition at line 103 of file MVExprArray.h.
References isTerminal(), LHS, OP, RHS, and Val.
Referenced by simplifyIndex().
deleteRhs()
void macveth::MVExprArray::MVAffineIndex::deleteRhs () inline
Delete safely the RHS of the expression.
Definition at line 117 of file MVExprArray.h.
References isTerminal(), LHS, OP, RHS, and Val.
Referenced by simplifyIndex().
isTerminal()
bool macveth::MVExprArray::MVAffineIndex::isTerminal () inline
Check if index is terminal or not (has real Val)
Definition at line 55 of file MVExprArray.h.
References LHS, RHS, and Val.
Referenced by deleteLhs(), deleteRhs(), operator-(), simplifyIndex(), toString(), and updateIndex().
operator-()
int macveth::MVExprArray::MVAffineIndex::operator- (const MVAffineIndex & M) inline
Definition at line 307 of file MVExprArray.h.
References isTerminal(), LHS, OP, RHS, and Val.
setVal()
void macveth::MVExprArray::MVAffineIndex::setVal (std::string Val) inline
If we set a Val, then there it has no leaves.
Definition at line 96 of file MVExprArray.h.
References Val.
Referenced by simplifyIndex().
simplifyIndex()
void macveth::MVExprArray::MVAffineIndex::simplifyIndex () inline
Simplify expression in order to better calculate indices and so.
Definition at line 131 of file MVExprArray.h.
References deleteLhs(), deleteRhs(), isTerminal(), setVal(), and Val.
Referenced by MVAffineIndex(), and updateIndex().
toString()
std::string macveth::MVExprArray::MVAffineIndex::toString () inline
Convert to string recursively.
Definition at line 374 of file MVExprArray.h.
References isTerminal(), toString(), and Val.
Referenced by toString().
updateIndex()
bool macveth::MVExprArray::MVAffineIndex::updateIndex (int UF, std::string LL, bool SubstituteVal) inline
Update index recursively.
Definition at line 261 of file MVExprArray.h.
References isTerminal(), MVAffineIndex(), RHS, simplifyIndex(), Unrolled, and updateIndex().
Referenced by updateIndex().
Member Data Documentation
LHS
MVAffineIndex* macveth::MVExprArray::MVAffineIndex::LHS = nullptr
Left part of the expression, if it has.
Definition at line 43 of file MVExprArray.h.
Referenced by copy(), deleteLhs(), deleteRhs(), isTerminal(), MVAffineIndex(), and operator-().
OP
clang::BinaryOperator::Opcode macveth::MVExprArray::MVAffineIndex::OP
BinaryOperator of the expression if it has any.
Definition at line 52 of file MVExprArray.h.
Referenced by copy(), deleteLhs(), deleteRhs(), MVAffineIndex(), and operator-().
RHS
MVAffineIndex* macveth::MVExprArray::MVAffineIndex::RHS = nullptr
Right part of the expression, if it has.
Definition at line 45 of file MVExprArray.h.
Referenced by copy(), deleteLhs(), deleteRhs(), isTerminal(), MVAffineIndex(), operator-(), and updateIndex().
Unrolled
std::map<std::string, bool> macveth::MVExprArray::MVAffineIndex::Unrolled
Unrolled.
Definition at line 50 of file MVExprArray.h.
Referenced by copy(), MVAffineIndex(), and updateIndex().
Val
std::string macveth::MVExprArray::MVAffineIndex::Val = ""
FIXME: Value of the expression (we do not care of its type, we handle strings)
Definition at line 48 of file MVExprArray.h.
Referenced by copy(), deleteLhs(), deleteRhs(), isTerminal(), MVAffineIndex(), operator-(), setVal(), simplifyIndex(), and toString().
The documentation for this struct was generated from the following file:
MACVETH/include/MVExpr/MVExprArray.h