MACVETH: macveth::MVExprArray Class Reference
macveth::MVExprArray Class Reference
Abstraction of arrays for simplicity.
#include "include/MVExpr/MVExprArray.h"
Classes
struct MVAffineIndex
Abstraction to handle affine indices in MACVETH.
Public Types
using IdxVector = std::vector< MVAffineIndex >
Definition of a vector of indices.
Public Types inherited from macveth::MVExpr
enum MVExprKind { MVK_Array, MVK_Literal, MVK_Var, MVK_Other }
Types of MVExpr.
enum MVExprInfo { EXPR_CLANG, TAC_EXPR, TMP_RES }
A MVExpr can be created from a clang::Expr or from a string, it can be an array a literal or even a variable, but when it comes to unroll, it is not the same if it is a temporal expression created ad-hoc (e.g.
Public Member Functions
virtual ~MVExprArray ()
Destructor.
MVExprArray (Expr *E)
Basic constructor.
MVExprArray (MVExprArray *E)
Copy constructor.
std::string getBaseName ()
Get base name.
IdxVector getIndex ()
Get index.
virtual std::string toString () const
To string.
std::string toStringWithOffset (int Offset)
FIXME: this is garbage.
virtual MVExpr * unrollExpr (int UF, std::string LL, bool SubstituteVal=false) override
Implementation of unrolling for arrays.
virtual int operator- (const MVExpr &MVE) override
As we may not know the total size of the array at compilation time, we can only know the difference between two indices.
Public Member Functions inherited from macveth::MVExpr
virtual ~MVExpr ()
Destructor.
MVExpr (MVExpr *TE)
Clone constructor.
MVExpr (MVExprKind K, std::string E)
Create MVExpr from string.
MVExpr (MVExprKind K, Expr *E)
Create MVExpr from clang::Expr, which sets its inner type/info to EXPR_CLANG.
void setTempInfo (MVExprInfo TempInfo)
Set info.
MVExprInfo getTempInfo ()
Get MVExpr info.
void setClangExpr (clang::Expr *ClangExpr)
Set clang::Expr attribute.
clang::Expr * getClangExpr () const
Get clang::Expr attribute.
void setTypeStr (std::string TypeStr)
Set type as a string.
std::string getTypeStr ()
Get type as a string.
void setExprStr (std::string ExprStr)
Set expression as an string.
std::string getExprStr () const
Get expression as an string.
std::string getExprStrRaw () const
Get the expression as a "raw" string.
void setKind (MVExprKind Kind)
Set kind of the expression.
MVExprKind getKind () const
Get kind of the expression.
bool isNotClang ()
This method allows to check whether the expression belongs or not to the original AST created by Clang.
virtual MVExpr * unrollExpr (std::unordered_map< int, std::string > LList)
Given a MVExpr and the map of unrolled,loop_level, it will return the unrolled version.
void setLoadFromMem ()
If this function is called, then the expression is in memory.
void setDoNotLoadFromMem ()
If this function is called, then the expression is not in memory.
bool needsToBeLoaded ()
Check if expression is in memory or not.
bool operator== (const MVExpr &MVE) const
Two expressions are equal if and only if their name or original code expression is equal, regardless where they appear in code.
bool operator!= (MVExpr &MVE)
Two expressions are not equal if and only if their name or original code expression is not equal.
Static Public Member Functions
static bool classof (const MVExpr *S)
In order to be able to use RTTI.
Detailed Description
Abstraction of arrays for simplicity.
Definition at line 38 of file MVExprArray.h.
Member Typedef Documentation
IdxVector
using macveth::MVExprArray::IdxVector = std::vector<MVAffineIndex>
Definition of a vector of indices.
Definition at line 386 of file MVExprArray.h.
Constructor & Destructor Documentation
~MVExprArray()
virtual macveth::MVExprArray::~MVExprArray () inline virtual
Destructor.
Definition at line 389 of file MVExprArray.h.
MVExprArray() [1/2]
macveth::MVExprArray::MVExprArray (Expr * E) inline
Basic constructor.
Definition at line 392 of file MVExprArray.h.
References macveth::Utils::getStringFromExpr(), and MACVETH_DEBUG.
MVExprArray() [2/2]
macveth::MVExprArray::MVExprArray (MVExprArray * E) inline
Copy constructor.
Definition at line 410 of file MVExprArray.h.
References macveth::MVExprArray::MVAffineIndex::copy().
Member Function Documentation
classof()
static bool macveth::MVExprArray::classof (const MVExpr * S) inline static
In order to be able to use RTTI.
Definition at line 460 of file MVExprArray.h.
References macveth::MVExpr::getKind(), and macveth::MVExpr::MVK_Array.
getBaseName()
std::string macveth::MVExprArray::getBaseName () inline
Get base name.
Definition at line 420 of file MVExprArray.h.
getIndex()
IdxVector macveth::MVExprArray::getIndex () inline
Get index.
Definition at line 423 of file MVExprArray.h.
operator-()
virtual int macveth::MVExprArray::operator- (const MVExpr & MVE) inline override virtual
As we may not know the total size of the array at compilation time, we can only know the difference between two indices.
Reimplemented from macveth::MVExpr.
Definition at line 450 of file MVExprArray.h.
References macveth::MVExpr::getClangExpr().
toString()
virtual std::string macveth::MVExprArray::toString () const inline virtual
To string.
Implements macveth::MVExpr.
Definition at line 426 of file MVExprArray.h.
toStringWithOffset()
std::string macveth::MVExprArray::toStringWithOffset (int Offset) inline
FIXME: this is garbage.
Definition at line 435 of file MVExprArray.h.
unrollExpr()
virtual MVExpr* macveth::MVExprArray::unrollExpr (int UF, std::string LL, bool SubstituteVal = false) override virtual
Implementation of unrolling for arrays.
In this case we will need to create a new MVExpr
Implements macveth::MVExpr.
The documentation for this class was generated from the following file:
include/MVExpr/MVExprArray.h