MACVETH: macveth::MVExprVar Class Reference
macveth::MVExprVar Class Reference
Abstraction of variables for simplicity.
#include "include/MVExpr/MVExprVar.h"
Public Member Functions
virtual ~MVExprVar ()
Destructor.
MVExprVar (MVExprVar *E)
MVExprVar (Expr *E)
MVExprVar (std::string E)
MVExprVar (std::string E, bool Temp)
virtual std::string toString () const
To string.
virtual MVExpr * unrollExpr (int UF, std::string LL, bool SubstituteVal=false)
Unroll expression.
Public Member Functions inherited from macveth::MVExpr
virtual ~MVExpr ()
Destructor.
MVExpr (MVExpr *TE)
Clone constructor.
MVExpr (MVExprKind K, std::string E)
Create MVExpr from string.
MVExpr (MVExprKind K, Expr *E)
Create MVExpr from clang::Expr, which sets its inner type/info to EXPR_CLANG.
void setTempInfo (MVExprInfo TempInfo)
Set info.
MVExprInfo getTempInfo ()
Get MVExpr info.
void setClangExpr (clang::Expr *ClangExpr)
Set clang::Expr attribute.
clang::Expr * getClangExpr () const
Get clang::Expr attribute.
void setTypeStr (std::string TypeStr)
Set type as a string.
std::string getTypeStr ()
Get type as a string.
void setExprStr (std::string ExprStr)
Set expression as an string.
std::string getExprStr () const
Get expression as an string.
std::string getExprStrRaw () const
Get the expression as a "raw" string.
void setKind (MVExprKind Kind)
Set kind of the expression.
MVExprKind getKind () const
Get kind of the expression.
bool isNotClang ()
This method allows to check whether the expression belongs or not to the original AST created by Clang.
virtual MVExpr * unrollExpr (std::unordered_map< int, std::string > LList)
Given a MVExpr and the map of unrolled,loop_level, it will return the unrolled version.
void setLoadFromMem ()
If this function is called, then the expression is in memory.
void setDoNotLoadFromMem ()
If this function is called, then the expression is not in memory.
bool needsToBeLoaded ()
Check if expression is in memory or not.
bool operator== (const MVExpr &MVE) const
Two expressions are equal if and only if their name or original code expression is equal, regardless where they appear in code.
bool operator!= (MVExpr &MVE)
Two expressions are not equal if and only if their name or original code expression is not equal.
virtual int operator- (const MVExpr &MVE)
Operators.
Static Public Member Functions
static bool hasBeenUnrolled (std::string Reg, std::string Dim)
Check if this has been unrolled.
static void regUnrollDim (MVExpr *MVE, std::string Dim, int UF)
Unroll register.
static void regUndoUnrollDim (MVExpr *MVE, std::string Dim, int UF)
Undo unrolled register.
static bool classof (const MVExpr *S)
In order to be able to use RTTI.
Static Public Attributes
static std::map< std::string, std::list< std::string > > RegDimUnrolled
Map to register the dimensions unrolled.
Additional Inherited Members
Public Types inherited from macveth::MVExpr
enum MVExprKind { MVK_Array, MVK_Literal, MVK_Var, MVK_Other }
Types of MVExpr.
enum MVExprInfo { EXPR_CLANG, TAC_EXPR, TMP_RES }
A MVExpr can be created from a clang::Expr or from a string, it can be an array a literal or even a variable, but when it comes to unroll, it is not the same if it is a temporal expression created ad-hoc (e.g.
Detailed Description
Abstraction of variables for simplicity.
Definition at line 37 of file MVExprVar.h.
Constructor & Destructor Documentation
~MVExprVar()
virtual macveth::MVExprVar::~MVExprVar () inline virtual
Destructor.
Definition at line 40 of file MVExprVar.h.
MVExprVar() [1/4]
macveth::MVExprVar::MVExprVar (MVExprVar * E) inline
Definition at line 41 of file MVExprVar.h.
MVExprVar() [2/4]
macveth::MVExprVar::MVExprVar (Expr * E) inline
Definition at line 42 of file MVExprVar.h.
MVExprVar() [3/4]
macveth::MVExprVar::MVExprVar (std::string E) inline
Definition at line 43 of file MVExprVar.h.
MVExprVar() [4/4]
macveth::MVExprVar::MVExprVar (std::string E, bool Temp) inline
Definition at line 44 of file MVExprVar.h.
References macveth::MVExpr::setTempInfo().
Member Function Documentation
classof()
static bool macveth::MVExprVar::classof (const MVExpr * S) inline static
In order to be able to use RTTI.
Definition at line 65 of file MVExprVar.h.
References macveth::MVExpr::getKind(), and macveth::MVExpr::MVK_Var.
hasBeenUnrolled()
static bool macveth::MVExprVar::hasBeenUnrolled (std::string Reg, std::string Dim) static
Check if this has been unrolled.
regUndoUnrollDim()
static void macveth::MVExprVar::regUndoUnrollDim (MVExpr * MVE, std::string Dim, int UF) static
Undo unrolled register.
regUnrollDim()
static void macveth::MVExprVar::regUnrollDim (MVExpr * MVE, std::string Dim, int UF) static
Unroll register.
toString()
virtual std::string macveth::MVExprVar::toString () const inline virtual
To string.
Implements macveth::MVExpr.
Definition at line 53 of file MVExprVar.h.
References macveth::MVExpr::getExprStrRaw().
unrollExpr()
virtual MVExpr* macveth::MVExprVar::unrollExpr (int UF, std::string LL, bool SubstituteVal = false) virtual
Unroll expression.
Implements macveth::MVExpr.
Member Data Documentation
RegDimUnrolled
std::map<std::string, std::list<std::string> > macveth::MVExprVar::RegDimUnrolled inline static
Map to register the dimensions unrolled.
Definition at line 67 of file MVExprVar.h.
The documentation for this class was generated from the following file:
include/MVExpr/MVExprVar.h