MACVETH: macveth::Node Class Reference
macveth::Node Class Reference
All Nodes belong to a CDAG.
#include "include/Node.h"
Classes
struct OutputInfo
If the node is NODE_OP type, then it will hold a result value.
struct SchedInfo
Holds information regarding the scheduling for this Node.
Public Types
enum NodeType { NODE_MEM, NODE_STORE, NODE_OP, UNDEF }
Available types of nodes.
enum OutputType { TEMP_STORE, MEM_STORE }
Types of stores for NODE_OP Node.
using NodeListType = std::vector< Node * >
Definition of NodeListType.
Public Member Functions
OutputInfo setOutputInfo (TAC T)
Set the output information of the given a TAC.
void setNodeAsReduction ()
void setNodeAsNonReduction ()
bool belongsToAReduction ()
void setSchedInfo ()
Setting the scheduling info without any other information.
void setOutputExpr (MVExpr *E)
Update the output expression.
void setSchedInfo (TAC T)
Setting the scheduling info without any other information than the TAC.
Node (MVExpr *TE)
When creating a Node from a TempExpr, the connections will be created by the TAC which creates this Node.
Node (const Node &Rhs)
Copy constructor for cloning.
Node (TAC T)
This is the unique constructor for nodes, as we will creating Nodes from CDAG, so each TAC corresponds to a = b op c.
Node (TAC T, NodeListType L)
This is the unique constructor for nodes, as we will creating Nodes from CDAG, so each TAC corresponds to a = b op c.
void updateIfStore ()
Update output information of the node if the type of the output is a memory store.
MVExpr * getMVExpr ()
Get MVExpr.
void setFreeSchedInfo (int FS)
Schedule info is needed for the algorithms to perform permutations in nodes.
void setTacID (int TacID)
Set the TAC order.
void setPlcmnt (int Plcmnt)
Set Plcmnt value.
void connectInput (Node *N)
Connect a Node as input.
std::vector< int > getScop ()
Get the scope of the node.
OutputInfo getOutputInfo ()
Get the output information.
std::string getOutputInfoName ()
Get the output information.
MVExpr * getOutputMVExpr ()
Get the output information.
int getInputNum ()
Get the number of inputs in this Node.
NodeListType getInputs ()
Get the list of node inputs in this Node.
SchedInfo getSchedInfo ()
Get info regarding its scheduling.
int getTacID ()
Get TAC order.
int getUnrollFactor ()
Get unrolling factor.
void setNodeType (NodeType T)
Set the type of the node.
std::string getDataType ()
Get data type of MVExpr as string.
bool hasInputs ()
Checks if input list is zero.
bool needsMemLoad ()
Is OP.
bool isStoreNodeOp ()
Check if Node type is NODE_STORE.
NodeType getNodeType ()
Get the node type.
std::string getValue () const
Returns the string value of the node.
std::string getRegisterValue () const
Returns the variable/register value.
std::string getLoopName ()
std::string toString ()
std::string toStringShort ()
int operator- (const Node &N)
This is useful for calculating the difference between two Nodes in terms of addresses, in some way.
bool operator== (const Node &N)
Two nodes are equal if and only if they have the same value: output value (if output nodes) or node value.
bool operator== (const Node *N)
Two nodes are equal if and only if they have the same value: output value (if output nodes) or node value.
bool operator!= (const Node &N)
Two nodes are not equal if and only if they are not equal (defined in operator==)
bool operator< (const Node &N)
Precedence of nodes is defined by the scheduling information.
std::string getSchedInfoStr ()
For debugging purposes: show information regarding the scheduling of the node.
Static Public Member Functions
static void restart ()
Restart UUID numbering.
static Node * findOutputNode (std::string NodeName, NodeListType L)
Check if Node N is already in node list L.
Static Public Attributes
static int UUID = 0
Simply universal identifier for each instance node.
Detailed Description
All Nodes belong to a CDAG.
Each node or vertex holds information regarding the type of operation as well as its Edges (or links to another Nodes). Nodes also hold information regarding the scheduling, i.e. the order on which they are consumed.
Definition at line 44 of file Node.h.
Member Typedef Documentation
NodeListType
using macveth::Node::NodeListType = std::vector<Node *>
Definition of NodeListType.
Definition at line 56 of file Node.h.
Member Enumeration Documentation
NodeType
enum macveth::Node::NodeType
Available types of nodes.
Enumerator
NODE_MEM
NODE_STORE
NODE_OP
UNDEF
Definition at line 59 of file Node.h.
OutputType
enum macveth::Node::OutputType
Types of stores for NODE_OP Node.
Enumerator
TEMP_STORE
MEM_STORE
Definition at line 62 of file Node.h.
Constructor & Destructor Documentation
Node() [1/4]
macveth::Node::Node (MVExpr * TE) inline
When creating a Node from a TempExpr, the connections will be created by the TAC which creates this Node.
Definition at line 130 of file Node.h.
References macveth::MVExpr::getExprStr(), NODE_MEM, and setSchedInfo().
Referenced by Node().
Node() [2/4]
macveth::Node::Node (const Node & Rhs) inline
Copy constructor for cloning.
Definition at line 138 of file Node.h.
Node() [3/4]
macveth::Node::Node (TAC T) inline
This is the unique constructor for nodes, as we will creating Nodes from CDAG, so each TAC corresponds to a = b op c.
Definition at line 149 of file Node.h.
References connectInput(), macveth::TAC::getB(), macveth::TAC::getC(), macveth::TAC::getLoopName(), macveth::TAC::getMVOP(), Node(), NODE_OP, setOutputInfo(), setSchedInfo(), macveth::MVOp::toString(), and updateIfStore().
Node() [4/4]
macveth::Node::Node (TAC T, NodeListType L) inline
This is the unique constructor for nodes, as we will creating Nodes from CDAG, so each TAC corresponds to a = b op c.
Definition at line 165 of file Node.h.
References connectInput(), findOutputNode(), macveth::TAC::getB(), macveth::TAC::getC(), macveth::MVExpr::getExprStr(), macveth::TAC::getLoopName(), macveth::TAC::getMVOP(), getScop(), Node(), NODE_OP, setOutputInfo(), setSchedInfo(), macveth::MVOp::toString(), and updateIfStore().
Member Function Documentation
belongsToAReduction()
bool macveth::Node::belongsToAReduction () inline
Definition at line 111 of file Node.h.
References macveth::Node::SchedInfo::IsReduction.
Referenced by operator<().
connectInput()
void macveth::Node::connectInput (Node * N)
Connect a Node as input.
Referenced by Node().
findOutputNode()
static Node* macveth::Node::findOutputNode (std::string NodeName, NodeListType L) static
Check if Node N is already in node list L.
Referenced by Node().
getDataType()
std::string macveth::Node::getDataType () inline
Get data type of MVExpr as string.
Definition at line 247 of file Node.h.
References macveth::Node::OutputInfo::E, and macveth::MVExpr::getTypeStr().
getInputNum()
int macveth::Node::getInputNum () inline
Get the number of inputs in this Node.
Definition at line 234 of file Node.h.
getInputs()
NodeListType macveth::Node::getInputs () inline
Get the list of node inputs in this Node.
Definition at line 236 of file Node.h.
Referenced by updateIfStore().
getLoopName()
std::string macveth::Node::getLoopName () inline
Definition at line 277 of file Node.h.
getMVExpr()
MVExpr* macveth::Node::getMVExpr () inline
Get MVExpr.
Definition at line 206 of file Node.h.
getNodeType()
NodeType macveth::Node::getNodeType () inline
Get the node type.
Definition at line 264 of file Node.h.
getOutputInfo()
OutputInfo macveth::Node::getOutputInfo () inline
Get the output information.
Definition at line 228 of file Node.h.
getOutputInfoName()
std::string macveth::Node::getOutputInfoName () inline
Get the output information.
Definition at line 230 of file Node.h.
References macveth::Node::OutputInfo::E, and macveth::MVExpr::toString().
getOutputMVExpr()
MVExpr* macveth::Node::getOutputMVExpr () inline
Get the output information.
Definition at line 232 of file Node.h.
References macveth::Node::OutputInfo::E.
getRegisterValue()
std::string macveth::Node::getRegisterValue () const inline
Returns the variable/register value.
Definition at line 270 of file Node.h.
References macveth::Node::OutputInfo::E, getValue(), and macveth::MVExpr::toString().
Referenced by operator==().
getSchedInfo()
SchedInfo macveth::Node::getSchedInfo () inline
Get info regarding its scheduling.
Definition at line 238 of file Node.h.
Referenced by getSchedInfoStr(), and operator<().
getSchedInfoStr()
std::string macveth::Node::getSchedInfoStr () inline
For debugging purposes: show information regarding the scheduling of the node.
Definition at line 339 of file Node.h.
References getSchedInfo(), and macveth::Node::SchedInfo::Scop.
getScop()
std::vector<int> macveth::Node::getScop () inline
Get the scope of the node.
Definition at line 225 of file Node.h.
References macveth::Node::SchedInfo::Scop.
Referenced by Node(), and updateIfStore().
getTacID()
int macveth::Node::getTacID () inline
Get TAC order.
Definition at line 240 of file Node.h.
References macveth::Node::SchedInfo::TacID.
Referenced by updateIfStore().
getUnrollFactor()
int macveth::Node::getUnrollFactor () inline
Get unrolling factor.
Definition at line 242 of file Node.h.
References macveth::Node::SchedInfo::UnrollFactor.
Referenced by updateIfStore().
getValue()
std::string macveth::Node::getValue () const inline
Returns the string value of the node.
Definition at line 267 of file Node.h.
Referenced by getRegisterValue().
hasInputs()
bool macveth::Node::hasInputs ()
Checks if input list is zero.
isStoreNodeOp()
bool macveth::Node::isStoreNodeOp () inline
Check if Node type is NODE_STORE.
Definition at line 261 of file Node.h.
References NODE_STORE.
needsMemLoad()
bool macveth::Node::needsMemLoad () inline
Is OP.
Definition at line 255 of file Node.h.
References macveth::MVExpr::needsToBeLoaded(), and NODE_MEM.
operator!=()
bool macveth::Node::operator!= (const Node & N) inline
Two nodes are not equal if and only if they are not equal (defined in operator==)
Definition at line 301 of file Node.h.
References operator==().
operator-()
int macveth::Node::operator- (const Node & N) inline
This is useful for calculating the difference between two Nodes in terms of addresses, in some way.
Definition at line 285 of file Node.h.
operator<()
bool macveth::Node::operator< (const Node & N) inline
Precedence of nodes is defined by the scheduling information.
Definition at line 304 of file Node.h.
References belongsToAReduction(), macveth::Node::SchedInfo::FreeSched, getSchedInfo(), macveth::Node::SchedInfo::IsReduction, macveth::Node::SchedInfo::NodeID, macveth::Node::SchedInfo::TacID, and macveth::Node::SchedInfo::UnrollFactor.
operator==() [1/2]
bool macveth::Node::operator== (const Node & N) inline
Two nodes are equal if and only if they have the same value: output value (if output nodes) or node value.
Definition at line 289 of file Node.h.
References getRegisterValue().
Referenced by operator!=().
operator==() [2/2]
bool macveth::Node::operator== (const Node * N) inline
Two nodes are equal if and only if they have the same value: output value (if output nodes) or node value.
Definition at line 295 of file Node.h.
References getRegisterValue().
restart()
static void macveth::Node::restart () inline static
Restart UUID numbering.
Definition at line 53 of file Node.h.
References UUID.
setFreeSchedInfo()
void macveth::Node::setFreeSchedInfo (int FS) inline
Schedule info is needed for the algorithms to perform permutations in nodes.
Definition at line 210 of file Node.h.
References macveth::Node::SchedInfo::FreeSched.
setNodeAsNonReduction()
void macveth::Node::setNodeAsNonReduction () inline
Definition at line 110 of file Node.h.
References macveth::Node::SchedInfo::IsReduction.
setNodeAsReduction()
void macveth::Node::setNodeAsReduction () inline
Definition at line 109 of file Node.h.
References macveth::Node::SchedInfo::IsReduction.
setNodeType()
void macveth::Node::setNodeType (NodeType T) inline
Set the type of the node.
Definition at line 244 of file Node.h.
setOutputExpr()
void macveth::Node::setOutputExpr (MVExpr * E) inline
Update the output expression.
Definition at line 117 of file Node.h.
References macveth::Node::OutputInfo::E.
setOutputInfo()
OutputInfo macveth::Node::setOutputInfo (TAC T) inline
Set the output information of the given a TAC.
Definition at line 100 of file Node.h.
References macveth::CLANG_BINOP, macveth::Node::OutputInfo::E, macveth::TAC::getA(), macveth::TAC::getMVOP(), macveth::MVOp::getType(), macveth::MVOp::isAssignment(), macveth::Node::OutputInfo::IsBinaryOp, MEM_STORE, macveth::Node::OutputInfo::MVOP, TEMP_STORE, and macveth::Node::OutputInfo::Type.
Referenced by Node().
setPlcmnt()
void macveth::Node::setPlcmnt (int Plcmnt) inline
Set Plcmnt value.
Definition at line 216 of file Node.h.
References macveth::Node::SchedInfo::Plcmnt.
setSchedInfo() [1/2]
void macveth::Node::setSchedInfo () inline
Setting the scheduling info without any other information.
Definition at line 114 of file Node.h.
References macveth::Node::SchedInfo::NodeID, and UUID.
Referenced by Node().
setSchedInfo() [2/2]
void macveth::Node::setSchedInfo (TAC T) inline
Setting the scheduling info without any other information than the TAC.
Definition at line 120 of file Node.h.
References macveth::TAC::getScop(), macveth::TAC::getTacID(), macveth::TAC::getUnrollFactor(), macveth::Node::SchedInfo::NodeID, macveth::Node::SchedInfo::Scop, macveth::Node::SchedInfo::TacID, macveth::Node::SchedInfo::UnrollFactor, and UUID.
setTacID()
void macveth::Node::setTacID (int TacID) inline
Set the TAC order.
Definition at line 213 of file Node.h.
References macveth::Node::SchedInfo::TacID.
toString()
std::string macveth::Node::toString ()
toStringShort()
std::string macveth::Node::toStringShort ()
updateIfStore()
void macveth::Node::updateIfStore () inline
Update output information of the node if the type of the output is a memory store.
Definition at line 192 of file Node.h.
References getInputs(), getScop(), getTacID(), getUnrollFactor(), MEM_STORE, NODE_STORE, and macveth::Node::OutputInfo::Type.
Referenced by Node().
Member Data Documentation
UUID
int macveth::Node::UUID = 0 inline static
Simply universal identifier for each instance node.
We have to be cautious with this value: it does not identify the object itself. Thus, whenever this object is cloned, this value is also cloned to the new object
Definition at line 50 of file Node.h.
Referenced by restart(), and setSchedInfo().
The documentation for this class was generated from the following file:
include/Node.h