MACVETH: macveth::CPUID Class Reference
macveth::CPUID Class Reference
#include "include/CPUID.h"
Public Member Functions
CPUID (unsigned FuncId, unsigned SubFuncId)
const uint32_t & EAX () const
Return EAX register.
const uint32_t & EBX () const
Return EBX register.
const uint32_t & ECX () const
Return ECX register.
const uint32_t & EDX () const
Return EDX register.
Detailed Description
Definition at line 45 of file CPUID.h.
Constructor & Destructor Documentation
CPUID()
macveth::CPUID::CPUID (unsigned FuncId, unsigned SubFuncId) inline explicit
Definition at line 50 of file CPUID.h.
Member Function Documentation
EAX()
const uint32_t& macveth::CPUID::EAX () const inline
Return EAX register.
Definition at line 62 of file CPUID.h.
Referenced by macveth::MVCPUInfo::MVCPUInfo().
EBX()
const uint32_t& macveth::CPUID::EBX () const inline
Return EBX register.
Definition at line 64 of file CPUID.h.
Referenced by macveth::MVCPUInfo::MVCPUInfo().
ECX()
const uint32_t& macveth::CPUID::ECX () const inline
Return ECX register.
Definition at line 66 of file CPUID.h.
Referenced by macveth::MVCPUInfo::MVCPUInfo().
EDX()
const uint32_t& macveth::CPUID::EDX () const inline
Return EDX register.
Definition at line 68 of file CPUID.h.
Referenced by macveth::MVCPUInfo::MVCPUInfo().
The documentation for this class was generated from the following file:
include/CPUID.h