MACVETH: macveth::MVSourceLocation Class Reference
macveth::MVSourceLocation Class Reference
MVSourceLocation serves to identify the order of certain instructions, such as reductions, initializations, etc.
#include "include/MVSourceLocation.h"
Public Types
enum Position {
PREOUTERMOST, PREORDER, INORDER, POSORDER,
POSOUTERMOST
}
Position specifies where the statement should be placed.
Public Member Functions
bool isPreOutermost ()
bool isPreOrder ()
bool isInOrder ()
bool isPosOrder ()
bool isPosOutermost ()
int getOffset ()
Get the order.
void setOffset (unsigned int Offset)
unsigned int getOrder ()
Get the order.
void setOrder (unsigned int Order)
Set order.
Position getPosition ()
Get the position.
void setPosition (Position P)
MVSourceLocation ()
Empty constructor.
MVSourceLocation (Position P)
Constructor given position.
MVSourceLocation (Position P, unsigned int Order)
Constructor given position and order.
MVSourceLocation (Position P, unsigned int Order, int Offset)
Constructor given position, order and offset.
bool operator== (MVSourceLocation M)
Detailed Description
MVSourceLocation serves to identify the order of certain instructions, such as reductions, initializations, etc.
Definition at line 32 of file MVSourceLocation.h.
Member Enumeration Documentation
Position
enum macveth::MVSourceLocation::Position
Position specifies where the statement should be placed.
Enumerator
PREOUTERMOST
Place before a certain loop nest.
PREORDER
Before the TAC. This is useful for initializations.
INORDER
Where the TAC is originally.
POSORDER
After the TAC.
This is useful for statements that changed their location due to transformations, e.g. loops
POSOUTERMOST
Place after nested loops.
Definition at line 35 of file MVSourceLocation.h.
Constructor & Destructor Documentation
MVSourceLocation() [1/4]
macveth::MVSourceLocation::MVSourceLocation () inline
Empty constructor.
Definition at line 88 of file MVSourceLocation.h.
MVSourceLocation() [2/4]
macveth::MVSourceLocation::MVSourceLocation (Position P) inline
Constructor given position.
Definition at line 91 of file MVSourceLocation.h.
MVSourceLocation() [3/4]
macveth::MVSourceLocation::MVSourceLocation (Position P, unsigned int Order) inline
Constructor given position and order.
Definition at line 94 of file MVSourceLocation.h.
MVSourceLocation() [4/4]
macveth::MVSourceLocation::MVSourceLocation (Position P, unsigned int Order, int Offset) inline
Constructor given position, order and offset.
Definition at line 100 of file MVSourceLocation.h.
Member Function Documentation
getOffset()
int macveth::MVSourceLocation::getOffset () inline
Get the order.
Definition at line 70 of file MVSourceLocation.h.
Referenced by operator==().
getOrder()
unsigned int macveth::MVSourceLocation::getOrder () inline
Get the order.
Definition at line 76 of file MVSourceLocation.h.
Referenced by operator==().
getPosition()
Position macveth::MVSourceLocation::getPosition () inline
Get the position.
Definition at line 82 of file MVSourceLocation.h.
Referenced by isInOrder(), isPosOrder(), isPosOutermost(), isPreOrder(), isPreOutermost(), and operator==().
isInOrder()
bool macveth::MVSourceLocation::isInOrder () inline
Definition at line 57 of file MVSourceLocation.h.
References getPosition().
isPosOrder()
bool macveth::MVSourceLocation::isPosOrder () inline
Definition at line 61 of file MVSourceLocation.h.
References getPosition().
isPosOutermost()
bool macveth::MVSourceLocation::isPosOutermost () inline
Definition at line 65 of file MVSourceLocation.h.
References getPosition().
isPreOrder()
bool macveth::MVSourceLocation::isPreOrder () inline
Definition at line 53 of file MVSourceLocation.h.
References getPosition().
isPreOutermost()
bool macveth::MVSourceLocation::isPreOutermost () inline
Definition at line 49 of file MVSourceLocation.h.
References getPosition().
operator==()
bool macveth::MVSourceLocation::operator== (MVSourceLocation M) inline
Definition at line 106 of file MVSourceLocation.h.
References getOffset(), getOrder(), and getPosition().
setOffset()
void macveth::MVSourceLocation::setOffset (unsigned int Offset) inline
Definition at line 73 of file MVSourceLocation.h.
setOrder()
void macveth::MVSourceLocation::setOrder (unsigned int Order) inline
Set order.
Definition at line 79 of file MVSourceLocation.h.
setPosition()
void macveth::MVSourceLocation::setPosition (Position P) inline
Definition at line 85 of file MVSourceLocation.h.
The documentation for this class was generated from the following file:
include/MVSourceLocation.h