MACVETH: macveth::TAC Class Reference
macveth::TAC Class Reference
Class TAC: three-address-code.
#include "include/TAC.h"
Public Member Functions
TAC ()
Empty constructor.
~TAC ()
Destructor.
TAC (MVExpr *A, MVExpr *B, MVExpr *C, MVOp MVOP)
Constructor when using MVOp for the operator.
TAC (MVExpr *A, MVExpr *B, MVExpr *C, MVOp MVOP, int TacID)
Constructor given a TAC ID.
MVExpr * getA ()
Get first (result) operand of the TAC expression.
void setA (MVExpr *A)
Set first (result) operand of the TAC expression.
MVExpr * getB ()
Get second operand of the TAC expression.
void setB (MVExpr *B)
Set second operand of the TAC expression.
MVExpr * getC ()
Get third operand of the TAC expression.
void setC (MVExpr *C)
Set third operand of the TAC expression.
void setTacID (int TacID)
Set TacID value.
void setScop (long TScop)
Set scope of the TAC.
long getScop ()
Get the scope of the TAC.
int getTacID ()
Get that TacID value.
int getUnrollFactor ()
Get the unroll factor.
void setLoopName (std::string LoopName)
Set loop name.
std::string getLoopName ()
Get loop name.
MVOp getMVOP ()
Get macveth operation type.
std::string toString ()
To string method.
Static Public Member Functions
static void clear ()
static std::list< TAC > stmtToTAC (clang::Stmt *ST)
Inserts TACs in the input TacList and outputs the relation between the statements and the ordering of the TACs.
static std::string renderTacAsStmt (std::list< TAC > TL, int Offset)
Print/render TAC as regular statements.
static std::list< TAC > unrollTacList (std::list< TAC > Tac, int UnrollFactor, int UpperBound, std::string LoopLevel, bool FullUnroll=false)
Unrolls TacList given onto a new list.
static TAC unroll (TAC Tac, int UnrollFactor, std::string LoopLevel, bool FullUnroll=false)
Unroll a TAC given a LoopLevel, besides its mask, unroll factor, and the S value which holds the iteration of the unrolling basically.
Static Public Attributes
static int TacUUID = 0
Unique ID of each TAC.
static long TacScop = 0
Unique ID of each region of each part of the #pragma.
static long RegVal = 0
For generating TACs.
Detailed Description
Class TAC: three-address-code.
This abstraction is a way of representing the Single-Statement Assignment (SSA). This class is meant to hold structures such as: a = b op c Where a, b and c are Expr and op is an Opcode
Definition at line 48 of file TAC.h.
Constructor & Destructor Documentation
TAC() [1/3]
macveth::TAC::TAC () inline
Empty constructor.
Definition at line 68 of file TAC.h.
~TAC()
macveth::TAC::~TAC () inline
Destructor.
Definition at line 71 of file TAC.h.
TAC() [2/3]
macveth::TAC::TAC (MVExpr * A, MVExpr * B, MVExpr * C, MVOp MVOP) inline
Constructor when using MVOp for the operator.
Definition at line 74 of file TAC.h.
TAC() [3/3]
macveth::TAC::TAC (MVExpr * A, MVExpr * B, MVExpr * C, MVOp MVOP, int TacID) inline
Constructor given a TAC ID.
Definition at line 78 of file TAC.h.
Member Function Documentation
clear()
static void macveth::TAC::clear () inline static
Unique ID of each TAC
Unique ID of each region of each part of the #pragma
For generating TACs
Definition at line 58 of file TAC.h.
getA()
MVExpr* macveth::TAC::getA () inline
Get first (result) operand of the TAC expression.
Definition at line 82 of file TAC.h.
Referenced by macveth::Node::setOutputInfo().
getB()
MVExpr* macveth::TAC::getB () inline
Get second operand of the TAC expression.
Definition at line 86 of file TAC.h.
Referenced by macveth::Node::Node().
getC()
MVExpr* macveth::TAC::getC () inline
Get third operand of the TAC expression.
Definition at line 90 of file TAC.h.
Referenced by macveth::Node::Node().
getLoopName()
std::string macveth::TAC::getLoopName () inline
Get loop name.
Definition at line 106 of file TAC.h.
Referenced by macveth::Node::Node().
getMVOP()
MVOp macveth::TAC::getMVOP () inline
Get macveth operation type.
Definition at line 109 of file TAC.h.
References macveth::MVOP.
Referenced by macveth::Node::Node(), and macveth::Node::setOutputInfo().
getScop()
long macveth::TAC::getScop () inline
Get the scope of the TAC.
Definition at line 98 of file TAC.h.
Referenced by macveth::Node::setSchedInfo().
getTacID()
int macveth::TAC::getTacID () inline
Get that TacID value.
Definition at line 100 of file TAC.h.
Referenced by macveth::Node::setSchedInfo().
getUnrollFactor()
int macveth::TAC::getUnrollFactor () inline
Get the unroll factor.
Definition at line 102 of file TAC.h.
Referenced by macveth::Node::setSchedInfo().
renderTacAsStmt()
static std::string macveth::TAC::renderTacAsStmt (std::list< TAC > TL, int Offset) static
Print/render TAC as regular statements.
setA()
void macveth::TAC::setA (MVExpr * A) inline
Set first (result) operand of the TAC expression.
Definition at line 84 of file TAC.h.
setB()
void macveth::TAC::setB (MVExpr * B) inline
Set second operand of the TAC expression.
Definition at line 88 of file TAC.h.
setC()
void macveth::TAC::setC (MVExpr * C) inline
Set third operand of the TAC expression.
Definition at line 92 of file TAC.h.
setLoopName()
void macveth::TAC::setLoopName (std::string LoopName) inline
Set loop name.
Definition at line 104 of file TAC.h.
setScop()
void macveth::TAC::setScop (long TScop) inline
Set scope of the TAC.
Definition at line 96 of file TAC.h.
setTacID()
void macveth::TAC::setTacID (int TacID) inline
Set TacID value.
Definition at line 94 of file TAC.h.
stmtToTAC()
static std::list<TAC> macveth::TAC::stmtToTAC (clang::Stmt * ST) static
Inserts TACs in the input TacList and outputs the relation between the statements and the ordering of the TACs.
toString()
std::string macveth::TAC::toString () inline
To string method.
Definition at line 112 of file TAC.h.
References macveth::MVOP.
unroll()
static TAC macveth::TAC::unroll (TAC Tac, int UnrollFactor, std::string LoopLevel, bool FullUnroll = false) static
Unroll a TAC given a LoopLevel, besides its mask, unroll factor, and the S value which holds the iteration of the unrolling basically.
unrollTacList()
static std::list<TAC> macveth::TAC::unrollTacList (std::list< TAC > Tac, int UnrollFactor, int UpperBound, std::string LoopLevel, bool FullUnroll = false) static
Unrolls TacList given onto a new list.
Member Data Documentation
RegVal
long macveth::TAC::RegVal = 0 inline static
For generating TACs.
Definition at line 56 of file TAC.h.
TacScop
long macveth::TAC::TacScop = 0 inline static
Unique ID of each region of each part of the #pragma.
Definition at line 54 of file TAC.h.
TacUUID
int macveth::TAC::TacUUID = 0 inline static
Unique ID of each TAC.
Definition at line 52 of file TAC.h.
The documentation for this class was generated from the following file:
include/TAC.h