MACVETH: macveth::MVExpr Class Reference
macveth::MVExpr Class Reference abstract
Expressions in MACVETH inherit from MVExpr.
#include "include/MVExpr/MVExpr.h"
Public Types
enum MVExprKind { MVK_Array, MVK_Literal, MVK_Var, MVK_Other }
Types of MVExpr.
enum MVExprInfo { EXPR_CLANG, TAC_EXPR, TMP_RES }
A MVExpr can be created from a clang::Expr or from a string, it can be an array a literal or even a variable, but when it comes to unroll, it is not the same if it is a temporal expression created ad-hoc (e.g.
Public Member Functions
virtual ~MVExpr ()
Destructor.
MVExpr (MVExpr *TE)
Clone constructor.
MVExpr (MVExprKind K, std::string E)
Create MVExpr from string.
MVExpr (MVExprKind K, Expr *E)
Create MVExpr from clang::Expr, which sets its inner type/info to EXPR_CLANG.
void setTempInfo (MVExprInfo TempInfo)
Set info.
MVExprInfo getTempInfo ()
Get MVExpr info.
void setClangExpr (clang::Expr *ClangExpr)
Set clang::Expr attribute.
clang::Expr * getClangExpr () const
Get clang::Expr attribute.
void setTypeStr (std::string TypeStr)
Set type as a string.
std::string getTypeStr ()
Get type as a string.
void setExprStr (std::string ExprStr)
Set expression as an string.
virtual std::string toString () const =0
To string function.
std::string getExprStr () const
Get expression as an string.
std::string getExprStrRaw () const
Get the expression as a "raw" string.
void setKind (MVExprKind Kind)
Set kind of the expression.
MVExprKind getKind () const
Get kind of the expression.
bool isNotClang ()
This method allows to check whether the expression belongs or not to the original AST created by Clang.
virtual MVExpr * unrollExpr (int UF, std::string LL, bool SubstituteVal=false)=0
Given a MVExpr it will return its unrolled version.
virtual MVExpr * unrollExpr (std::unordered_map< int, std::string > LList)
Given a MVExpr and the map of unrolled,loop_level, it will return the unrolled version.
void setLoadFromMem ()
If this function is called, then the expression is in memory.
void setDoNotLoadFromMem ()
If this function is called, then the expression is not in memory.
bool needsToBeLoaded ()
Check if expression is in memory or not.
bool operator== (const MVExpr &MVE) const
Two expressions are equal if and only if their name or original code expression is equal, regardless where they appear in code.
bool operator!= (MVExpr &MVE)
Two expressions are not equal if and only if their name or original code expression is not equal.
virtual int operator- (const MVExpr &MVE)
Operators.
Detailed Description
Expressions in MACVETH inherit from MVExpr.
This class holds a double identity for expressions: a string name (for debugging purposes and for clarity) and the actual Clang Expr, for transformations. Besides, it also "simplifies" the typing of the expression to some defined types (MVExprType). This will help to calculate offsets and to simplify the Clang AST typing.
Definition at line 51 of file MVExpr.h.
Member Enumeration Documentation
MVExprInfo
enum macveth::MVExpr::MVExprInfo
A MVExpr can be created from a clang::Expr or from a string, it can be an array a literal or even a variable, but when it comes to unroll, it is not the same if it is a temporal expression created ad-hoc (e.g.
tempX register which holds a temporal value in the TAC representation). This way, we can distinguish those cases.
Enumerator
EXPR_CLANG
TAC_EXPR
TMP_RES
Definition at line 70 of file MVExpr.h.
MVExprKind
enum macveth::MVExpr::MVExprKind
Types of MVExpr.
Enumerator
MVK_Array
Defined in MVExprArray.
MVK_Literal
Defined in MVExprLiteral.
MVK_Var
Defined in MVExprVar.
MVK_Other
Other.
Definition at line 54 of file MVExpr.h.
Constructor & Destructor Documentation
~MVExpr()
virtual macveth::MVExpr::~MVExpr () inline virtual
Destructor.
Definition at line 73 of file MVExpr.h.
MVExpr() [1/3]
macveth::MVExpr::MVExpr (MVExpr * TE) inline
Clone constructor.
Definition at line 76 of file MVExpr.h.
References getClangExpr(), getExprStr(), getKind(), getTempInfo(), and getTypeStr().
MVExpr() [2/3]
macveth::MVExpr::MVExpr (MVExprKind K, std::string E) inline
Create MVExpr from string.
In this case we will assume we are treating with a TAC_EXPR
Definition at line 86 of file MVExpr.h.
MVExpr() [3/3]
macveth::MVExpr::MVExpr (MVExprKind K, Expr * E) inline
Create MVExpr from clang::Expr, which sets its inner type/info to EXPR_CLANG.
Definition at line 92 of file MVExpr.h.
References MACVETH_DEBUG.
Member Function Documentation
getClangExpr()
clang::Expr* macveth::MVExpr::getClangExpr () const inline
Get clang::Expr attribute.
Definition at line 123 of file MVExpr.h.
Referenced by MVExpr(), macveth::MVExprArray::operator-(), and macveth::MVExprLiteral::toString().
getExprStr()
std::string macveth::MVExpr::getExprStr () const inline
Get expression as an string.
Definition at line 152 of file MVExpr.h.
Referenced by MVExpr(), macveth::Node::Node(), and operator==().
getExprStrRaw()
std::string macveth::MVExpr::getExprStrRaw () const inline
Get the expression as a "raw" string.
Should avoid this if the object is volatile meaning for that it can change, e.g. a[i] when parsed can be converted as a string "a[i]". However, if we unroll the value then we will still have "a[i]" instead of "a[i+unroll]". That is why toString() is way more powerful
Definition at line 159 of file MVExpr.h.
Referenced by macveth::MVExprVar::toString().
getKind()
MVExprKind macveth::MVExpr::getKind () const inline
Get kind of the expression.
Definition at line 165 of file MVExpr.h.
Referenced by macveth::MVExprLiteral::classof(), macveth::MVExprVar::classof(), macveth::MVExprArray::classof(), and MVExpr().
getTempInfo()
MVExprInfo macveth::MVExpr::getTempInfo () inline
Get MVExpr info.
Definition at line 117 of file MVExpr.h.
Referenced by MVExpr().
getTypeStr()
std::string macveth::MVExpr::getTypeStr () inline
Get type as a string.
Definition at line 143 of file MVExpr.h.
Referenced by macveth::Node::getDataType(), and MVExpr().
isNotClang()
bool macveth::MVExpr::isNotClang () inline
This method allows to check whether the expression belongs or not to the original AST created by Clang.
Definition at line 169 of file MVExpr.h.
needsToBeLoaded()
bool macveth::MVExpr::needsToBeLoaded () inline
Check if expression is in memory or not.
Definition at line 188 of file MVExpr.h.
Referenced by macveth::Node::needsMemLoad().
operator!=()
bool macveth::MVExpr::operator!= (MVExpr & MVE) inline
Two expressions are not equal if and only if their name or original code expression is not equal.
Definition at line 198 of file MVExpr.h.
operator-()
virtual int macveth::MVExpr::operator- (const MVExpr & MVE) inline virtual
Operators.
Reimplemented in macveth::MVExprArray.
Definition at line 201 of file MVExpr.h.
operator==()
bool macveth::MVExpr::operator== (const MVExpr & MVE) const inline
Two expressions are equal if and only if their name or original code expression is equal, regardless where they appear in code.
Definition at line 192 of file MVExpr.h.
References getExprStr().
setClangExpr()
void macveth::MVExpr::setClangExpr (clang::Expr * ClangExpr) inline
Set clang::Expr attribute.
Definition at line 120 of file MVExpr.h.
setDoNotLoadFromMem()
void macveth::MVExpr::setDoNotLoadFromMem () inline
If this function is called, then the expression is not in memory.
Definition at line 185 of file MVExpr.h.
setExprStr()
void macveth::MVExpr::setExprStr (std::string ExprStr) inline
Set expression as an string.
Definition at line 146 of file MVExpr.h.
setKind()
void macveth::MVExpr::setKind (MVExprKind Kind) inline
Set kind of the expression.
Definition at line 162 of file MVExpr.h.
setLoadFromMem()
void macveth::MVExpr::setLoadFromMem () inline
If this function is called, then the expression is in memory.
Definition at line 182 of file MVExpr.h.
setTempInfo()
void macveth::MVExpr::setTempInfo (MVExprInfo TempInfo) inline
Set info.
Definition at line 114 of file MVExpr.h.
Referenced by macveth::MVExprVar::MVExprVar().
setTypeStr()
void macveth::MVExpr::setTypeStr (std::string TypeStr) inline
Set type as a string.
Definition at line 126 of file MVExpr.h.
toString()
virtual std::string macveth::MVExpr::toString () const pure virtual
To string function.
Implemented in macveth::MVExprArray, macveth::MVExprVar, and macveth::MVExprLiteral.
Referenced by macveth::Node::getOutputInfoName(), and macveth::Node::getRegisterValue().
unrollExpr() [1/2]
virtual MVExpr* macveth::MVExpr::unrollExpr (int UF, std::string LL, bool SubstituteVal = false) pure virtual
Given a MVExpr it will return its unrolled version.
Implemented in macveth::MVExprArray, macveth::MVExprVar, and macveth::MVExprLiteral.
unrollExpr() [2/2]
virtual MVExpr* macveth::MVExpr::unrollExpr (std::unordered_map< int, std::string > LList) inline virtual
Given a MVExpr and the map of unrolled,loop_level, it will return the unrolled version.
Definition at line 177 of file MVExpr.h.
The documentation for this class was generated from the following file:
include/MVExpr/MVExpr.h