MACVETH: lib/macveth.cpp File Reference
macveth.cpp File Reference
#include "lib/macveth.h"
#include "include/MVFrontend.h"
#include "include/MVOptions.h"
#include "include/MVPragmaHandler.h"
#include "include/Utils.h"
#include "clang/Format/Format.h"
#include "clang/Tooling/CommonOptionsParser.h"
#include "clang/Tooling/Tooling.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Signals.h"
Macros
#define DEBUG 0
Functions
static llvm::cl::OptionCategory MacvethCategory ("Macveth Options")
static llvm::cl::extrahelp CommonHelp (CommonOptionsParser::HelpMessage)
static llvm::cl::opt< std::string > OutputFile ("o", cl::cat(MacvethCategory), llvm::cl::desc("Output file to write the code, otherwise " "it will just print int std output"))
static llvm::cl::opt< std::string > SIMDInfoFile ("simd-info", cl::cat(MacvethCategory), llvm::cl::desc("Report with all the SIMD information"))
static llvm::cl::opt< std::string > SIMDInfoMissedFile ("simd-info-missed", cl::cat(MacvethCategory), llvm::cl::desc("Report with all missed SIMD opportunities"))
static llvm::cl::opt< std::string > TargetFunc ("func", cl::cat(MacvethCategory), llvm::cl::desc("Target function"))
static llvm::cl::opt< std::string > CDAGInFile ("input-cdag", cl::cat(MacvethCategory), llvm::cl::desc("Input file to read the custom CDAG placement"))
static llvm::cl::opt< MVSIMDCostModel > SIMDCostModel ("simd-cost-model", llvm::cl::desc("SIMD cost model"), llvm::cl::init(MVSIMDCostModel::CONSERVATIVE), cl::cat(MacvethCategory), llvm::cl::values(clEnumValN(MVSIMDCostModel::CONSERVATIVE, "conservative", "Vectorize if and only if the sequential estimation is " "worse than the vectorized"), clEnumValN(MVSIMDCostModel::AGGRESSIVE, "aggressive", "Vectorize partially if beneficial according to cost model"), clEnumValN(MVSIMDCostModel::UNLIMITED, "unlimited", "Unlimited SIMD cost, i.e. vectorize regardless the cost")))
static llvm::cl::opt< MVCPUInfo::MVISA > ISA ("misa", llvm::cl::desc("Target ISA"), llvm::cl::init(MVCPUInfo::MVISA::AUTODETECT), llvm::cl::cat(MacvethCategory), llvm::cl::values(clEnumValN(MVCPUInfo::MVISA::AUTODETECT, "native", "Detect ISA of the architecture"), clEnumValN(MVCPUInfo::MVISA::SSE, "sse", "SSE ISA"), clEnumValN(MVCPUInfo::MVISA::AVX, "avx", "AVX ISA"), clEnumValN(MVCPUInfo::MVISA::AVX2, "avx2", "AVX2 ISA"), clEnumValN(MVCPUInfo::MVISA::AVX512, "avx512", "AVX512 ISA")))
static llvm::cl::opt< MVCPUInfo::MVArch > Architecture ("arch", llvm::cl::desc("Target architecture"), llvm::cl::init(MVCPUInfo::MVArch::NATIVE), llvm::cl::cat(MacvethCategory), llvm::cl::values(clEnumValN(MVCPUInfo::MVArch::NATIVE, "native", "Detect the architecture"), clEnumValN(MVCPUInfo::MVArch::Nehalem, "nehalem", "Intel Nehalem (2009) architecture (tock): SSE4.2"), clEnumValN(MVCPUInfo::MVArch::Westmere, "westmere", "Intel Westmere (2010) architecture (tick): SSE4.2"), clEnumValN(MVCPUInfo::MVArch::SandyBridge, "sandybridge", "Intel SandyBridge (2011) architecture (tock): AVX"), clEnumValN(MVCPUInfo::MVArch::IvyBridge, "ivybridge", "Intel IvyBridge (2012) architecture (tick): AVX"), clEnumValN(MVCPUInfo::MVArch::Haswell, "haswell", "Intel Haswell (2013) architecture (tock): AVX2"), clEnumValN(MVCPUInfo::MVArch::Broadwell, "broadwell", "Intel Broadwell (2014) architecture (tick): AVX2"), clEnumValN(MVCPUInfo::MVArch::Skylake, "skylake", "Intel Skylake (2015) architecture (tock): AVX512"), clEnumValN(MVCPUInfo::MVArch::KabyLake, "kabylake", "Intel Kaby Lake (2016) architecture (tock): AVX2"), clEnumValN(MVCPUInfo::MVArch::CoffeeLake, "coffeelake", "Intel Coffee Lake (2017) architecture (tock): AVX2"), clEnumValN(MVCPUInfo::MVArch::CascadeLake, "cascadelake", "Intel Cascade Lake (2019) architecture (tock): AVX512"), clEnumValN(MVCPUInfo::MVArch::IceLake, "icelake", "Intel Ice Lake (2020) architecture (tick): AVX512"), clEnumValN(MVCPUInfo::MVArch::Zen, "zen", "AMD Zen (2019) architecture: AVX2"), clEnumValN(MVCPUInfo::MVArch::Zen2, "zen2", "AMD Zen 2 (2020) architecture: AVX2"), clEnumValN(MVCPUInfo::MVArch::AMDDef, "amd", "AMD architecture not specified"), clEnumValN(MVCPUInfo::MVArch::IntelDef, "intel", "Intel architecture not specified")))
static cl::opt< std::string > Style ("format-style", cl::desc("Coding style, currently supports:\n" " LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.\n" "Use -format-style=file to load style configuration from\n" ".clang-format file located in one of the parent\n" "directories of the source file (or current\n" "directory for stdin).\n" "Use -format-style=\"{key: value, ...}\" to set specific\n" "parameters, e.g.:\n" " -format-style=\"{BasedOnStyle: llvm, IndentWidth: 8}\""), cl::init(clang::format::DefaultFormatStyle), cl::cat(MacvethCategory))
static cl::opt< std::string > FallbackStyle ("format-fallback-style", cl::desc("The name of the predefined style used as a\n" "fallback in case clang-format is invoked with\n" "-format-style=file, but can not find the .clang-format\n" "file to use.\n" "Use -format-fallback-style=none to skip formatting."), cl::init(clang::format::DefaultFallbackStyle), cl::cat(MacvethCategory))
static llvm::cl::opt< bool > FMA ("fma", llvm::cl::desc("Support for FMA instructions"), llvm::cl::init(false), llvm::cl::cat(MacvethCategory))
static llvm::cl::opt< bool > ScatterInstruction ("scatter", llvm::cl::desc("Support AVX512 scatter instructions"), llvm::cl::init(false), llvm::cl::cat(MacvethCategory))
static llvm::cl::opt< bool > NoSVML ("no-svml", llvm::cl::desc("Disable Intrinsics SVML"), llvm::cl::init(false), llvm::cl::cat(MacvethCategory))
static llvm::cl::opt< bool > DisableFMA ("nofma", llvm::cl::desc("Explicitly tell to not generate FMA instructions even if " "architecture supports them"), llvm::cl::init(false), llvm::cl::cat(MacvethCategory))
static llvm::cl::opt< bool > Debug ("debug-mv", llvm::cl::desc("Print debug information"), llvm::cl::init(false), llvm::cl::cat(MacvethCategory))
static llvm::cl::opt< bool > NoFormatCode ("no-format", llvm::cl::desc("MACVETH by defaults reformats code as " "clang-format does, using LLVM style. If this option is " "enabled, then no reformatting is applied"), llvm::cl::init(false), llvm::cl::cat(MacvethCategory))
static llvm::cl::opt< bool > NoHeaders ("no-headers", llvm::cl::desc("If set, do *not* include header files, such as <immintrin.h>"), llvm::cl::init(false), llvm::cl::cat(MacvethCategory))
static llvm::cl::opt< std::string > DebugFile ("debug-file", cl::cat(MacvethCategory), llvm::cl::desc("Output file to print the debug information"))
int main (int argc, const char **argv)
Macro Definition Documentation
DEBUG
#define DEBUG 0
Definition at line 38 of file macveth.cpp.
Function Documentation
Architecture()
static llvm::cl::opt<MVCPUInfo::MVArch> Architecture ("arch" , llvm::cl::desc("Target architecture") , llvm::cl::init(MVCPUInfo::MVArch::NATIVE) , llvm::cl::cat(MacvethCategory) , llvm::cl::values(clEnumValN(MVCPUInfo::MVArch::NATIVE, "native", "Detect the architecture"), clEnumValN(MVCPUInfo::MVArch::Nehalem, "nehalem", "Intel Nehalem (2009) architecture (tock): SSE4.2"), clEnumValN(MVCPUInfo::MVArch::Westmere, "westmere", "Intel Westmere (2010) architecture (tick): SSE4.2"), clEnumValN(MVCPUInfo::MVArch::SandyBridge, "sandybridge", "Intel SandyBridge (2011) architecture (tock): AVX"), clEnumValN(MVCPUInfo::MVArch::IvyBridge, "ivybridge", "Intel IvyBridge (2012) architecture (tick): AVX"), clEnumValN(MVCPUInfo::MVArch::Haswell, "haswell", "Intel Haswell (2013) architecture (tock): AVX2"), clEnumValN(MVCPUInfo::MVArch::Broadwell, "broadwell", "Intel Broadwell (2014) architecture (tick): AVX2"), clEnumValN(MVCPUInfo::MVArch::Skylake, "skylake", "Intel Skylake (2015) architecture (tock): AVX512"), clEnumValN(MVCPUInfo::MVArch::KabyLake, "kabylake", "Intel Kaby Lake (2016) architecture (tock): AVX2"), clEnumValN(MVCPUInfo::MVArch::CoffeeLake, "coffeelake", "Intel Coffee Lake (2017) architecture (tock): AVX2"), clEnumValN(MVCPUInfo::MVArch::CascadeLake, "cascadelake", "Intel Cascade Lake (2019) architecture (tock): AVX512"), clEnumValN(MVCPUInfo::MVArch::IceLake, "icelake", "Intel Ice Lake (2020) architecture (tick): AVX512"), clEnumValN(MVCPUInfo::MVArch::Zen, "zen", "AMD Zen (2019) architecture: AVX2"), clEnumValN(MVCPUInfo::MVArch::Zen2, "zen2", "AMD Zen 2 (2020) architecture: AVX2"), clEnumValN(MVCPUInfo::MVArch::AMDDef, "amd", "AMD architecture not specified"), clEnumValN(MVCPUInfo::MVArch::IntelDef, "intel", "Intel architecture not specified"))) static
Referenced by main().
CDAGInFile()
static llvm::cl::opt<std::string> CDAGInFile ("input-cdag" , cl::cat(MacvethCategory) , llvm::cl::desc("Input file to read the custom CDAG placement")) static
Referenced by main().
CommonHelp()
static llvm::cl::extrahelp CommonHelp (CommonOptionsParser::HelpMessage) static
Debug()
static llvm::cl::opt<bool> Debug ("debug-mv" , llvm::cl::desc("Print debug information") , llvm::cl::init(false) , llvm::cl::cat(MacvethCategory)) static
Referenced by main().
DebugFile()
static llvm::cl::opt<std::string> DebugFile ("debug-file" , cl::cat(MacvethCategory) , llvm::cl::desc("Output file to print the debug information")) static
Referenced by main().
DisableFMA()
static llvm::cl::opt<bool> DisableFMA ("nofma" , llvm::cl::desc("Explicitly tell to not generate FMA instructions even if " "architecture supports them") , llvm::cl::init(false) , llvm::cl::cat(MacvethCategory)) static
Referenced by main().
FallbackStyle()
static cl::opt<std::string> FallbackStyle ("format-fallback-style" , cl::desc("The name of the predefined style used as a\n" "fallback in case clang-format is invoked with\n" "-format-style=file, but can not find the .clang-format\n" "file to use.\n" "Use -format-fallback-style=none to skip formatting.") , cl::init(clang::format::DefaultFallbackStyle) , cl::cat(MacvethCategory)) static
Referenced by main().
FMA()
static llvm::cl::opt<bool> FMA ("fma" , llvm::cl::desc("Support for FMA instructions") , llvm::cl::init(false) , llvm::cl::cat(MacvethCategory)) static
Referenced by main().
ISA()
static llvm::cl::opt<MVCPUInfo::MVISA> ISA ("misa" , llvm::cl::desc("Target ISA") , llvm::cl::init(MVCPUInfo::MVISA::AUTODETECT) , llvm::cl::cat(MacvethCategory) , llvm::cl::values(clEnumValN(MVCPUInfo::MVISA::AUTODETECT, "native", "Detect ISA of the architecture"), clEnumValN(MVCPUInfo::MVISA::SSE, "sse", "SSE ISA"), clEnumValN(MVCPUInfo::MVISA::AVX, "avx", "AVX ISA"), clEnumValN(MVCPUInfo::MVISA::AVX2, "avx2", "AVX2 ISA"), clEnumValN(MVCPUInfo::MVISA::AVX512, "avx512", "AVX512 ISA"))) static
Referenced by macveth::SIMDBackEndFactory::getBackend(), and main().
MacvethCategory()
static llvm::cl::OptionCategory MacvethCategory ("Macveth Options") static
Referenced by main().
main()
int main (int argc, const char ** argv)
Definition at line 210 of file macveth.cpp.
References Architecture(), CDAGInFile(), DEBUG, Debug(), DebugFile(), DisableFMA(), FallbackStyle(), FMA(), ISA(), MacvethCategory(), NoFormatCode(), NoHeaders(), NoSVML(), OutputFile(), ScatterInstruction(), SIMDCostModel(), Style(), and TargetFunc().
NoFormatCode()
static llvm::cl::opt<bool> NoFormatCode ("no-format" , llvm::cl::desc("MACVETH by defaults reformats code as " "clang-format does, using LLVM style. If this option is " "enabled, then no reformatting is applied") , llvm::cl::init(false) , llvm::cl::cat(MacvethCategory)) static
Referenced by main().
NoHeaders()
static llvm::cl::opt<bool> NoHeaders ("no-headers" , llvm::cl::desc("If set, do *not* include header files, such as <immintrin.h>") , llvm::cl::init(false) , llvm::cl::cat(MacvethCategory)) static
Referenced by main().
NoSVML()
static llvm::cl::opt<bool> NoSVML ("no-svml" , llvm::cl::desc("Disable Intrinsics SVML") , llvm::cl::init(false) , llvm::cl::cat(MacvethCategory)) static
Referenced by main().
OutputFile()
static llvm::cl::opt<std::string> OutputFile ("o" , cl::cat(MacvethCategory) , llvm::cl::desc("Output file to write the code, otherwise " "it will just print int std output")) static
Referenced by main().
ScatterInstruction()
static llvm::cl::opt<bool> ScatterInstruction ("scatter" , llvm::cl::desc("Support AVX512 scatter instructions") , llvm::cl::init(false) , llvm::cl::cat(MacvethCategory)) static
Referenced by main().
SIMDCostModel()
static llvm::cl::opt<MVSIMDCostModel> SIMDCostModel ("simd-cost-model" , llvm::cl::desc("SIMD cost model") , llvm::cl::init(MVSIMDCostModel::CONSERVATIVE) , cl::cat(MacvethCategory) , llvm::cl::values(clEnumValN(MVSIMDCostModel::CONSERVATIVE, "conservative", "Vectorize if and only if the sequential estimation is " "worse than the vectorized"), clEnumValN(MVSIMDCostModel::AGGRESSIVE, "aggressive", "Vectorize partially if beneficial according to cost model"), clEnumValN(MVSIMDCostModel::UNLIMITED, "unlimited", "Unlimited SIMD cost, i.e. vectorize regardless the cost"))) static
Referenced by main().
SIMDInfoFile()
static llvm::cl::opt<std::string> SIMDInfoFile ("simd-info" , cl::cat(MacvethCategory) , llvm::cl::desc("Report with all the SIMD information")) static
SIMDInfoMissedFile()
static llvm::cl::opt<std::string> SIMDInfoMissedFile ("simd-info-missed" , cl::cat(MacvethCategory) , llvm::cl::desc("Report with all missed SIMD opportunities")) static
Style()
static cl::opt<std::string> Style ("format-style" , cl::desc("Coding style, currently supports:\n" " LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.\n" "Use -format-style=file to load style configuration from\n" ".clang-format file located in one of the parent\n" "directories of the source file (or current\n" "directory for stdin).\n" "Use -format-style=\"{key: value, ...}\" to set specific\n" "parameters, e.g.:\n" " -format-style=\"{BasedOnStyle: llvm, IndentWidth: 8}\"") , cl::init(clang::format::DefaultFormatStyle) , cl::cat(MacvethCategory)) static
Referenced by main().
TargetFunc()
static llvm::cl::opt<std::string> TargetFunc ("func" , cl::cat(MacvethCategory) , llvm::cl::desc("Target function")) static
Referenced by main().