MACVETH: macveth Namespace Reference
macveth Namespace Reference
Classes
class AVX2BackEnd
SIMD generator for AVX2 architectures.
class CDAG
Computation Directed Acyclic Graph (CDAG).
class CostTable
Auxiliary class which holds the operations equivalences for the different architectures.
class CPUID
struct InstCostInfo
Wrapper for calculating the cost of instructions.
class IntelIntrinsics
class MVConsumer
Implementation of the ASTConsumer interface for reading an AST produced by the Clang parser.
class MVCostModel
class MVCPUInfo
class MVDataType
class MVExpr
Expressions in MACVETH inherit from MVExpr.
class MVExprArray
Abstraction of arrays for simplicity.
class MVExprFactory
Create MVExpr depending on the dynamic cast clang does.
class MVExprLiteral
Abstraction of variables for simplicity.
class MVExprVar
Abstraction of variables for simplicity.
class MVFrontendAction
MACVETH Frontend which is in charge of creating the AST consumer and to write the changes to the output file.
class MVFuncVisitor
struct MVOp
MVOp is meant to identify those operations that Clang lacks.
struct MVOptions
Parse and hold information regarding CLI arguments.
class MVRewriter
class MVSourceLocation
MVSourceLocation serves to identify the order of certain instructions, such as reductions, initializations, etc.
class Node
All Nodes belong to a CDAG.
class PlcmntAlgo
struct PragmaEndScopHandler
Handle pragmas of the form.
struct PragmaScopHandler
Handle pragmas of the form.
struct ScopHandler
List of pairs of #pragma macveth and #pragma endmacveth source locations.
struct ScopLoc
The Location of the Scop, as delimited by macveth and endmacveth pragmas by the user.
class SIMDBackEnd
Abstract class implemented by each architecture (AVX, AVX2, AVX512, etc.) to generate specific intrinsics and calculate the associated cost for the operations provided by the VectorAPI.
class SIMDBackEndFactory
Wrapper for avoiding low level details when creating the different backends.
struct SIMDInfo
Return value when generating new code.
class StmtWrapper
StmtWrapper, as its name suggests, wraps statements, its TAC representation and the desired intrinsic translation.
class TAC
Class TAC: three-address-code.
class Utils
class VectorIR
VectorIR is a facade for the CDAG to compute the cost of the vectorization, generate intrinsics and perform the optimizations.
Typedefs
using PragmaTupleDim = std::vector< std::tuple< std::string, int > >
using TacListType = std::list< TAC >
List of TACs.
Enumerations
enum VectorizationType { NONE, PARTIAL, FULL }
Result of computation.
enum InstType { SIMDOp, MVOP }
Types of instruction.
enum MVOpType { CLANG_BINOP, MVFUNC }
MVOp possible types.
enum MVOpCode {
UNDEF, ADD, SUB, MUL,
DIV, EXP, POW, MAX,
MIN, AVG, CEIL, FLOOR,
ROUND, SIN, COS
}
Custom MVFUNC.
enum MVSIMDCostModel { UNLIMITED, CONSERVATIVE, AGGRESSIVE }
Costs models naming.
enum DebugLevel {
ALL = 0, LOW = 1, MID = 2, HIGH = 3,
TEST = 4
}
Functions
void MVAssertSkip (bool cond, std::string Msg, jmp_buf Goto, int Val=MVSkipCode)
If condition is false, then print message and goto the jump buffer.
void MVWarn (std::string Msg)
Print warning message.
void MVInfo (std::string Msg)
Print info message.
void MVAssert (bool cond, const char *Msg)
Hard assertion: if condition not satisfied print error and zeroed-exit.
void MVErr (std::string Msg)
Print error and zeroed-exit.
static IdentifierInfo * getValue (Token &token)
Get IdentifierInfo from Token.
static ScopLoc::PragmaArgs parseArguments (Preprocessor &PP)
Parse arguments using the preprocessor.
Variables
static int MVSkipCode = 11
static std::map< MVSIMDCostModel, std::string > CostModelStr
Map costs models to strings.
static std::map< MVCPUInfo::MVISA, std::string > MVISAStr
Mapping ISAs.
static std::map< MVCPUInfo::MVArch, std::string > MVArchStr
static std::map< MVCPUInfo::MVISA, std::list< MVCPUInfo::MVArch > > SupportedISAArch
Mapping between the ISA and supported architectures.
Typedef Documentation
PragmaTupleDim
using macveth::PragmaTupleDim = typedef std::vector<std::tuple<std::string, int> >
Definition at line 41 of file MVPragmaHandler.h.
TacListType
using macveth::TacListType = typedef std::list<TAC>
List of TACs.
Definition at line 162 of file TAC.h.
Enumeration Type Documentation
DebugLevel
enum macveth::DebugLevel
Enumerator
ALL
All levels below.
LOW
Very very verbose when creating the CDAG, TACs, etc.
MID
Checkpoints such as: TACs created, etc.
HIGH
For concrete functions.
TEST
When you are testing something.
Definition at line 113 of file MVOptions.h.
InstType
enum macveth::InstType
Types of instruction.
Enumerator
SIMDOp
SIMD type operation.
MVOP
MVOP is the same as sequential.
Definition at line 48 of file SIMDCostInfo.h.
MVOpCode
enum macveth::MVOpCode
Custom MVFUNC.
Enumerator
UNDEF
Operation not known/defined.
ADD
Addition.
SUB
Substraction.
MUL
Multiplication.
DIV
Division.
EXP
Exponential.
POW
Power.
MAX
Max operation.
MIN
Minimum.
AVG
Average value.
CEIL
Ceil values.
FLOOR
Floor values.
ROUND
Round values.
SIN
Sinus.
COS
Cosine.
Definition at line 43 of file MVOps.h.
MVOpType
enum macveth::MVOpType
MVOp possible types.
Enumerator
CLANG_BINOP
BinaryOperator::Opcode type.
MVFUNC
MVOpCode type.
Definition at line 35 of file MVOps.h.
MVSIMDCostModel
enum macveth::MVSIMDCostModel
Costs models naming.
Enumerator
UNLIMITED
Vectorize always, despite the not vectorized estimation cost.
CONSERVATIVE
If the sequential code vs the SIMD-zed code has a better estimation, then MACVETH does not vectorize the code.
AGGRESSIVE
Region to vectorize can have parts where vectorization provides better performance.
Definition at line 39 of file MVOptions.h.
VectorizationType
enum macveth::VectorizationType
Result of computation.
Enumerator
NONE
Do not vectorize anything.
PARTIAL
Perform partial vectorization.
FULL
Perform full vectorization.
Definition at line 38 of file SIMDCostInfo.h.
Function Documentation
getValue()
static IdentifierInfo* macveth::getValue (Token & token) static
Get IdentifierInfo from Token.
Definition at line 172 of file MVPragmaHandler.h.
Referenced by parseArguments().
MVAssert()
void macveth::MVAssert (bool cond, const char * Msg)
Hard assertion: if condition not satisfied print error and zeroed-exit.
Referenced by macveth::AVX2BackEnd::getMapWidth().
MVAssertSkip()
void macveth::MVAssertSkip (bool cond, std::string Msg, jmp_buf Goto, int Val = MVSkipCode)
If condition is false, then print message and goto the jump buffer.
Referenced by macveth::MVOp::getTypeFromStr().
MVErr()
void macveth::MVErr (std::string Msg)
Print error and zeroed-exit.
Referenced by macveth::SIMDBackEndFactory::getBackend(), macveth::VectorIR::VOperand::getRegName(), and parseArguments().
MVInfo()
void macveth::MVInfo (std::string Msg)
Print info message.
MVWarn()
void macveth::MVWarn (std::string Msg)
Print warning message.
Referenced by macveth::SIMDInfo::generateCostReport().
parseArguments()
static ScopLoc::PragmaArgs macveth::parseArguments (Preprocessor & PP) static
Parse arguments using the preprocessor.
Definition at line 183 of file MVPragmaHandler.h.
References macveth::ScopLoc::PragmaArgs::FullUnroll, getValue(), MVErr(), macveth::ScopLoc::PragmaArgs::SIMDCode, macveth::ScopLoc::PragmaArgs::Unroll, macveth::ScopLoc::PragmaArgs::UnrollAndJam, and macveth::ScopLoc::PragmaArgs::UnrollDim.
Referenced by macveth::PragmaScopHandler::HandlePragma().
Variable Documentation
CostModelStr
std::map<MVSIMDCostModel, std::string> macveth::CostModelStr static
Initial value:
= {
    {UNLIMITED, "unlimited"},
    {CONSERVATIVE, "conservative"},
    {AGGRESSIVE, "conservative"}}
Map costs models to strings.
Definition at line 51 of file MVOptions.h.
Referenced by macveth::MVOptions::toString().
MVArchStr
std::map<MVCPUInfo::MVArch, std::string> macveth::MVArchStr static
Initial value:
= {
    {MVCPUInfo::MVArch::DEFAULT, "Default"},
    {MVCPUInfo::MVArch::Nehalem, "Nehalem"},
    {MVCPUInfo::MVArch::Westmere, "Westmere"},
    {MVCPUInfo::MVArch::SandyBridge, "SandyBridge"},
    {MVCPUInfo::MVArch::IvyBridge, "IvyBridge"},
    {MVCPUInfo::MVArch::Haswell, "Haswell"},
    {MVCPUInfo::MVArch::Broadwell, "Broadwell"},
    {MVCPUInfo::MVArch::Skylake, "Skylake"},
    {MVCPUInfo::MVArch::KabyLake, "KabyLake"},
    {MVCPUInfo::MVArch::CoffeeLake, "CoffeeLake"},
    {MVCPUInfo::MVArch::CascadeLake, "CascadeLake"},
    {MVCPUInfo::MVArch::IceLake, "IceLake"},
    {MVCPUInfo::MVArch::Zen, "Zen"},
    {MVCPUInfo::MVArch::Zen2, "Zen2"},
    {MVCPUInfo::MVArch::AMDDef, "Zen"},
    {MVCPUInfo::MVArch::IntelDef, "Broadwell"}}
Definition at line 63 of file MVOptions.h.
Referenced by macveth::MVOptions::toString().
MVISAStr
std::map<MVCPUInfo::MVISA, std::string> macveth::MVISAStr static
Initial value:
= {
    {MVCPUInfo::MVISA::SSE, "SSE"},
    {MVCPUInfo::MVISA::AVX, "AVX"},
    {MVCPUInfo::MVISA::AVX2, "AVX2"},
    {MVCPUInfo::MVISA::AVX512, "AVX512"}}
Mapping ISAs.
Definition at line 57 of file MVOptions.h.
Referenced by macveth::MVOptions::toString().
MVSkipCode
int macveth::MVSkipCode = 11 inline static
Definition at line 76 of file MVAssert.h.
SupportedISAArch
std::map<MVCPUInfo::MVISA, std::list<MVCPUInfo::MVArch> > macveth::SupportedISAArch static
Initial value:
= {
        {MVCPUInfo::MVISA::SSE,
         {MVCPUInfo::MVArch::Nehalem, MVCPUInfo::MVArch::Westmere,
          MVCPUInfo::MVArch::SandyBridge, MVCPUInfo::MVArch::IvyBridge,
          MVCPUInfo::MVArch::Haswell, MVCPUInfo::MVArch::Broadwell,
          MVCPUInfo::MVArch::Skylake, MVCPUInfo::MVArch::KabyLake,
          MVCPUInfo::MVArch::CoffeeLake, MVCPUInfo::MVArch::CascadeLake,
          MVCPUInfo::MVArch::IceLake, MVCPUInfo::MVArch::Zen,
          MVCPUInfo::MVArch::Zen2, MVCPUInfo::MVArch::AMDDef,
          MVCPUInfo::MVArch::IntelDef}},
        {MVCPUInfo::MVISA::AVX,
         {MVCPUInfo::MVArch::SandyBridge, MVCPUInfo::MVArch::IvyBridge,
          MVCPUInfo::MVArch::Haswell, MVCPUInfo::MVArch::Broadwell,
          MVCPUInfo::MVArch::Skylake, MVCPUInfo::MVArch::KabyLake,
          MVCPUInfo::MVArch::CoffeeLake, MVCPUInfo::MVArch::CascadeLake,
          MVCPUInfo::MVArch::IceLake, MVCPUInfo::MVArch::Zen,
          MVCPUInfo::MVArch::Zen2, MVCPUInfo::MVArch::AMDDef,
          MVCPUInfo::MVArch::IntelDef}},
        {MVCPUInfo::MVISA::AVX2,
         {MVCPUInfo::MVArch::Haswell, MVCPUInfo::MVArch::Broadwell,
          MVCPUInfo::MVArch::Skylake, MVCPUInfo::MVArch::KabyLake,
          MVCPUInfo::MVArch::CoffeeLake, MVCPUInfo::MVArch::CascadeLake,
          MVCPUInfo::MVArch::IceLake, MVCPUInfo::MVArch::Zen,
          MVCPUInfo::MVArch::Zen2, MVCPUInfo::MVArch::AMDDef,
          MVCPUInfo::MVArch::IntelDef}},
        {MVCPUInfo::MVISA::AVX512,
         {MVCPUInfo::MVArch::Skylake, MVCPUInfo::MVArch::CascadeLake,
          MVCPUInfo::MVArch::IceLake, MVCPUInfo::MVArch::AMDDef,
          MVCPUInfo::MVArch::IntelDef}}}
Mapping between the ISA and supported architectures.
Definition at line 83 of file MVOptions.h.
Referenced by macveth::MVOptions::checkIfArchISACompatible().