MACVETH: macveth::MVOptions Struct Reference
macveth::MVOptions Struct Reference
Parse and hold information regarding CLI arguments.
#include "include/MVOptions.h"
Static Public Member Functions
static MVCPUInfo::MVArch getMVArch ()
static MVCPUInfo::MVISA getMVISA ()
static std::string toString ()
Print options as a string for reports and so.
static void validateOptions ()
Main function to check options of the compiler.
static void checkIfArchISACompatible ()
Dumb method to check compatibility between options.
Static Public Attributes
static std::string OutFile = ""
Name of the output file (-o=<file>)
static std::string InCDAGFile = ""
Name of the input CDAG file (-input-cdag=<file>)
static std::string OutDebugFile = ""
Name of the output debug file (-output-debug=<file>)
static std::string SIMDReportFile = ""
Name of the output debug file (-simd-info=<file>)
static std::string SIMDReportMissFile = ""
Name of the output debug file (-simd-info-missed=<file>)
static std::string Style = ""
Format style output.
static std::string FallbackStyle = ""
Fallback format style output.
static MVCPUInfo::MVISA ISA = MVCPUInfo::MVISA::AUTODETECT
Target ISA.
static MVCPUInfo::MVArch Arch = MVCPUInfo::MVArch::DEFAULT
Target architecture.
static bool FMASupport = false
FMA support.
static bool DisableFMA = false
Disable FMA support.
static bool ScatterInstruction = false
Enable use of scatter instruction.
static bool Debug = false
Print debug information.
static DebugLevel DLevel = DebugLevel::ALL
Debug level.
static bool NoReformat = false
No reformatting the final code.
static bool MacroCode = false
Generate or not macro-based code.
static bool Headers = true
Include headers (–no-headers)
static MVSIMDCostModel SIMDCostModel = MVSIMDCostModel::CONSERVATIVE
SIMD Cost model.
static bool IntrinsicsSVML = true
Intrinsics Short Vector Math Library (SVML)
static std::string TargetFunc = ""
Target function.
Detailed Description
Parse and hold information regarding CLI arguments.
Definition at line 127 of file MVOptions.h.
Member Function Documentation
checkIfArchISACompatible()
static void macveth::MVOptions::checkIfArchISACompatible () inline static
Dumb method to check compatibility between options.
Check incompatible options:
Definition at line 218 of file MVOptions.h.
References Arch, DisableFMA, FMASupport, ISA, and macveth::SupportedISAArch.
Referenced by validateOptions().
getMVArch()
static MVCPUInfo::MVArch macveth::MVOptions::getMVArch () inline static
Definition at line 169 of file MVOptions.h.
References macveth::MVCPUInfo::getArchitecture().
Referenced by validateOptions().
getMVISA()
static MVCPUInfo::MVISA macveth::MVOptions::getMVISA () inline static
Definition at line 174 of file MVOptions.h.
References macveth::MVCPUInfo::isAVX(), macveth::MVCPUInfo::isAVX2(), macveth::MVCPUInfo::isAVX512F(), and macveth::MVCPUInfo::isSSE42().
Referenced by validateOptions().
toString()
static std::string macveth::MVOptions::toString () inline static
Print options as a string for reports and so.
Definition at line 193 of file MVOptions.h.
References Arch, macveth::CostModelStr, DisableFMA, InCDAGFile, IntrinsicsSVML, ISA, macveth::MVArchStr, macveth::MVISAStr, OutDebugFile, OutFile, and SIMDCostModel.
validateOptions()
static void macveth::MVOptions::validateOptions () inline static
Main function to check options of the compiler.
Definition at line 207 of file MVOptions.h.
References Arch, checkIfArchISACompatible(), getMVArch(), getMVISA(), and ISA.
Member Data Documentation
Arch
MVCPUInfo::MVArch macveth::MVOptions::Arch = MVCPUInfo::MVArch::DEFAULT inline static
Target architecture.
Definition at line 145 of file MVOptions.h.
Referenced by checkIfArchISACompatible(), toString(), and validateOptions().
Debug
bool macveth::MVOptions::Debug = false inline static
Print debug information.
Definition at line 153 of file MVOptions.h.
DisableFMA
bool macveth::MVOptions::DisableFMA = false inline static
Disable FMA support.
Definition at line 149 of file MVOptions.h.
Referenced by checkIfArchISACompatible(), and toString().
DLevel
DebugLevel macveth::MVOptions::DLevel = DebugLevel::ALL inline static
Debug level.
Definition at line 155 of file MVOptions.h.
FallbackStyle
std::string macveth::MVOptions::FallbackStyle = "" inline static
Fallback format style output.
Definition at line 141 of file MVOptions.h.
FMASupport
bool macveth::MVOptions::FMASupport = false inline static
FMA support.
Definition at line 147 of file MVOptions.h.
Referenced by checkIfArchISACompatible().
Headers
bool macveth::MVOptions::Headers = true inline static
Include headers (–no-headers)
Definition at line 161 of file MVOptions.h.
InCDAGFile
std::string macveth::MVOptions::InCDAGFile = "" inline static
Name of the input CDAG file (-input-cdag=<file>)
Definition at line 131 of file MVOptions.h.
Referenced by toString().
IntrinsicsSVML
bool macveth::MVOptions::IntrinsicsSVML = true inline static
Intrinsics Short Vector Math Library (SVML)
Definition at line 165 of file MVOptions.h.
Referenced by macveth::MVOp::getTypeFromStr(), and toString().
ISA
MVCPUInfo::MVISA macveth::MVOptions::ISA = MVCPUInfo::MVISA::AUTODETECT inline static
Target ISA.
Definition at line 143 of file MVOptions.h.
Referenced by checkIfArchISACompatible(), toString(), and validateOptions().
MacroCode
bool macveth::MVOptions::MacroCode = false inline static
Generate or not macro-based code.
Definition at line 159 of file MVOptions.h.
NoReformat
bool macveth::MVOptions::NoReformat = false inline static
No reformatting the final code.
Definition at line 157 of file MVOptions.h.
OutDebugFile
std::string macveth::MVOptions::OutDebugFile = "" inline static
Name of the output debug file (-output-debug=<file>)
Definition at line 133 of file MVOptions.h.
Referenced by toString().
OutFile
std::string macveth::MVOptions::OutFile = "" inline static
Name of the output file (-o=<file>)
Definition at line 129 of file MVOptions.h.
Referenced by toString().
ScatterInstruction
bool macveth::MVOptions::ScatterInstruction = false inline static
Enable use of scatter instruction.
Definition at line 151 of file MVOptions.h.
SIMDCostModel
MVSIMDCostModel macveth::MVOptions::SIMDCostModel = MVSIMDCostModel::CONSERVATIVE inline static
SIMD Cost model.
Definition at line 163 of file MVOptions.h.
Referenced by toString().
SIMDReportFile
std::string macveth::MVOptions::SIMDReportFile = "" inline static
Name of the output debug file (-simd-info=<file>)
Definition at line 135 of file MVOptions.h.
Referenced by macveth::SIMDInfo::generateCostReport().
SIMDReportMissFile
std::string macveth::MVOptions::SIMDReportMissFile = "" inline static
Name of the output debug file (-simd-info-missed=<file>)
Definition at line 137 of file MVOptions.h.
Style
std::string macveth::MVOptions::Style = "" inline static
Format style output.
Definition at line 139 of file MVOptions.h.
TargetFunc
std::string macveth::MVOptions::TargetFunc = "" inline static
Target function.
Definition at line 167 of file MVOptions.h.
The documentation for this struct was generated from the following file:
include/MVOptions.h