MACVETH: macveth::StmtWrapper::LoopInfo Struct Reference
macveth::StmtWrapper::LoopInfo Struct Reference
Helper structure to handle the loop information for this statement.
#include "include/StmtWrapper.h"
Public Member Functions
LoopInfo ()
Empty constructor.
bool knownBounds ()
Check if bounds are known, i.e. if values are known at compiler time.
std::string getDim ()
std::string toString ()
For debugging purposes.
Static Public Member Functions
static std::string getEpilogs (StmtWrapper *SWrap)
Get epilogs given a StmtWrapper, which may contain loops within.
static std::string getDimDeclarations (std::list< std::string > DimsDeclared)
Get a list of the dimensions declared in the loop.
static void clearDims ()
Public Attributes
clang::SourceLocation BegLoc
Location of the loop itself.
clang::SourceLocation EndLoc
Location after the loop itself.
std::string Dim
Name of dimension.
long InitVal = -1
Initial value (-1 if not known)
std::string StrInitVal = ""
Initial value if it can not be evaluated.
long UpperBound = 0
Upperbound value (-1 if not known)
BinaryOperator::Opcode UpperBoundComp = BinaryOperator::Opcode::BO_LT
Comparator upperbound.
std::string StrUpperBound = ""
Upperbound as string.
long Step = UBFallback
Stride or step.
long StepUnrolled = UBFallback
Stride or step after unrolling.
long LeftOver = -1
TODO Leftover values: if Upperbound is -1, then LeftOver as well.
bool Declared = false
Variable declared in the loop creation.
int UnrollFactor = UBFallback
Unrolling factor.
bool FullyUnrolled = false
Full unroll.
clang::CharSourceRange SRVarInit
Location of the initialization in the loop.
clang::CharSourceRange SRVarCond
Location of the condition of the loop.
clang::CharSourceRange SRVarInc
Location of the increment in the loop.
Static Public Attributes
static std::list< std::string > DimDeclared = {}
List of dimensions declared.
Detailed Description
Helper structure to handle the loop information for this statement.
Definition at line 53 of file StmtWrapper.h.
Constructor & Destructor Documentation
LoopInfo()
macveth::StmtWrapper::LoopInfo::LoopInfo () inline
Empty constructor.
Definition at line 92 of file StmtWrapper.h.
Member Function Documentation
clearDims()
static void macveth::StmtWrapper::LoopInfo::clearDims () inline static
Definition at line 115 of file StmtWrapper.h.
References DimDeclared.
getDim()
std::string macveth::StmtWrapper::LoopInfo::getDim () inline
Definition at line 103 of file StmtWrapper.h.
References Dim.
Referenced by macveth::StmtWrapper::getInnerLoopName(), macveth::StmtWrapper::isInLoop(), and macveth::StmtWrapper::setInnerLoopInfo().
getDimDeclarations()
static std::string macveth::StmtWrapper::LoopInfo::getDimDeclarations (std::list< std::string > DimsDeclared) static
Get a list of the dimensions declared in the loop.
getEpilogs()
static std::string macveth::StmtWrapper::LoopInfo::getEpilogs (StmtWrapper * SWrap) static
Get epilogs given a StmtWrapper, which may contain loops within.
knownBounds()
bool macveth::StmtWrapper::LoopInfo::knownBounds () inline
Check if bounds are known, i.e. if values are known at compiler time.
Definition at line 95 of file StmtWrapper.h.
References InitVal, and UpperBound.
Referenced by toString().
toString()
std::string macveth::StmtWrapper::LoopInfo::toString () inline
For debugging purposes.
Definition at line 106 of file StmtWrapper.h.
References Declared, Dim, InitVal, knownBounds(), Step, StepUnrolled, and UpperBound.
Member Data Documentation
BegLoc
clang::SourceLocation macveth::StmtWrapper::LoopInfo::BegLoc
Location of the loop itself.
Definition at line 57 of file StmtWrapper.h.
Declared
bool macveth::StmtWrapper::LoopInfo::Declared = false
Variable declared in the loop creation.
Definition at line 79 of file StmtWrapper.h.
Referenced by toString().
Dim
std::string macveth::StmtWrapper::LoopInfo::Dim
Name of dimension.
Definition at line 61 of file StmtWrapper.h.
Referenced by getDim(), and toString().
DimDeclared
std::list<std::string> macveth::StmtWrapper::LoopInfo::DimDeclared = {} inline static
List of dimensions declared.
Definition at line 55 of file StmtWrapper.h.
Referenced by clearDims().
EndLoc
clang::SourceLocation macveth::StmtWrapper::LoopInfo::EndLoc
Location after the loop itself.
Definition at line 59 of file StmtWrapper.h.
FullyUnrolled
bool macveth::StmtWrapper::LoopInfo::FullyUnrolled = false
Full unroll.
Definition at line 83 of file StmtWrapper.h.
InitVal
long macveth::StmtWrapper::LoopInfo::InitVal = -1
Initial value (-1 if not known)
Definition at line 63 of file StmtWrapper.h.
Referenced by knownBounds(), and toString().
LeftOver
long macveth::StmtWrapper::LoopInfo::LeftOver = -1
TODO Leftover values: if Upperbound is -1, then LeftOver as well.
Definition at line 77 of file StmtWrapper.h.
SRVarCond
clang::CharSourceRange macveth::StmtWrapper::LoopInfo::SRVarCond
Location of the condition of the loop.
Definition at line 87 of file StmtWrapper.h.
SRVarInc
clang::CharSourceRange macveth::StmtWrapper::LoopInfo::SRVarInc
Location of the increment in the loop.
Definition at line 89 of file StmtWrapper.h.
SRVarInit
clang::CharSourceRange macveth::StmtWrapper::LoopInfo::SRVarInit
Location of the initialization in the loop.
Definition at line 85 of file StmtWrapper.h.
Step
long macveth::StmtWrapper::LoopInfo::Step = UBFallback
Stride or step.
Definition at line 73 of file StmtWrapper.h.
Referenced by toString().
StepUnrolled
long macveth::StmtWrapper::LoopInfo::StepUnrolled = UBFallback
Stride or step after unrolling.
Definition at line 75 of file StmtWrapper.h.
Referenced by toString().
StrInitVal
std::string macveth::StmtWrapper::LoopInfo::StrInitVal = ""
Initial value if it can not be evaluated.
Definition at line 65 of file StmtWrapper.h.
StrUpperBound
std::string macveth::StmtWrapper::LoopInfo::StrUpperBound = ""
Upperbound as string.
Definition at line 71 of file StmtWrapper.h.
UnrollFactor
int macveth::StmtWrapper::LoopInfo::UnrollFactor = UBFallback
Unrolling factor.
Definition at line 81 of file StmtWrapper.h.
UpperBound
long macveth::StmtWrapper::LoopInfo::UpperBound = 0
Upperbound value (-1 if not known)
Definition at line 67 of file StmtWrapper.h.
Referenced by knownBounds(), and toString().
UpperBoundComp
BinaryOperator::Opcode macveth::StmtWrapper::LoopInfo::UpperBoundComp = BinaryOperator::Opcode::BO_LT
Comparator upperbound.
Definition at line 69 of file StmtWrapper.h.
The documentation for this struct was generated from the following file:
include/StmtWrapper.h