MACVETH: macveth::MVOp Struct Reference
macveth::MVOp Struct Reference
MVOp is meant to identify those operations that Clang lacks.
#include "include/MVOps.h"
Public Member Functions
std::string getStrFromMVCode (MVOpCode C)
Return the equivalent string given a MVOpCode.
std::string getStrFromBinaryOperatorOpcode (clang::BinaryOperator::Opcode ClangOP)
Return the equivalent string given a MVOpCode.
bool isAssignment ()
Shortcut to check whether a MVOp is of type BO_Assign.
bool isBinaryOperation ()
Check whether the operation is binary or not.
bool isAddOrSub ()
Check whether the operation is an addition or a substraction.
std::string getTableMVOPstr (std::string T)
Get equivalent MVOP string for searching in the Table Cost.
std::string getPrefixFromStr (std::string S)
Get the namespace of the expression.
std::string toString ()
Convert MVOp to string.
std::string getOpPrefix ()
Get the prefix.
MVOpType getType ()
Return the type of the operation.
MVOp (std::string S)
Constructor given a string: will be a MVFUNC.
MVOp (clang::BinaryOperator::Opcode OP)
Given a BinaryOperator::Opcode the MVOp will be of CLANG_BINOP type.
MVOp ()
Empty constructor: UNDEF MVOp.
Static Public Member Functions
static MVOpCode getTypeFromStr (std::string S)
Given a string it returns the type of function based on the MVOpCode it is defined for this compiler.
Public Attributes
std::string Prefix = ""
Prefix.
MVOpType T
Type of the MVOp.
union {
clang::BinaryOperator::Opcode ClangOP
When CLANG_BINOP.
MVOpCode MVOpC
When MVFUNC.
};
We can handle Clang BinOps or MVOps.
Detailed Description
MVOp is meant to identify those operations that Clang lacks.
This way parsing is easier for backends and more extensible. It is implemented using a 'union' over 'std::variant' (C++14) since both possible types are enums and may have the same values; this way we can explicitly handle each case
Definition at line 80 of file MVOps.h.
Constructor & Destructor Documentation
MVOp() [1/3]
macveth::MVOp::MVOp (std::string S) inline
Constructor given a string: will be a MVFUNC.
Definition at line 231 of file MVOps.h.
References getPrefixFromStr(), getTypeFromStr(), macveth::MVFUNC, and MVOpC.
MVOp() [2/3]
macveth::MVOp::MVOp (clang::BinaryOperator::Opcode OP) inline
Given a BinaryOperator::Opcode the MVOp will be of CLANG_BINOP type.
Definition at line 238 of file MVOps.h.
References macveth::CLANG_BINOP, and ClangOP.
MVOp() [3/3]
macveth::MVOp::MVOp () inline
Empty constructor: UNDEF MVOp.
Definition at line 244 of file MVOps.h.
References macveth::MVFUNC, MVOpC, and macveth::UNDEF.
Member Function Documentation
getOpPrefix()
std::string macveth::MVOp::getOpPrefix () inline
Get the prefix.
Definition at line 225 of file MVOps.h.
References Prefix.
getPrefixFromStr()
std::string macveth::MVOp::getPrefixFromStr (std::string S) inline
Get the namespace of the expression.
Definition at line 206 of file MVOps.h.
Referenced by MVOp().
getStrFromBinaryOperatorOpcode()
std::string macveth::MVOp::getStrFromBinaryOperatorOpcode (clang::BinaryOperator::Opcode ClangOP) inline
Return the equivalent string given a MVOpCode.
Definition at line 162 of file MVOps.h.
References ClangOP.
Referenced by getTableMVOPstr().
getStrFromMVCode()
std::string macveth::MVOp::getStrFromMVCode (MVOpCode C) inline
Return the equivalent string given a MVOpCode.
Definition at line 126 of file MVOps.h.
References macveth::ADD, macveth::AVG, macveth::CEIL, macveth::COS, macveth::DIV, macveth::EXP, macveth::FLOOR, macveth::MAX, macveth::MIN, macveth::MUL, macveth::ROUND, macveth::SIN, and macveth::SUB.
Referenced by getTableMVOPstr(), and toString().
getTableMVOPstr()
std::string macveth::MVOp::getTableMVOPstr (std::string T) inline
Get equivalent MVOP string for searching in the Table Cost.
Definition at line 196 of file MVOps.h.
References macveth::CLANG_BINOP, ClangOP, getStrFromBinaryOperatorOpcode(), getStrFromMVCode(), getType(), MVOpC, T, and macveth::Utils::toUppercase().
getType()
MVOpType macveth::MVOp::getType () inline
Return the type of the operation.
Definition at line 228 of file MVOps.h.
References T.
Referenced by getTableMVOPstr(), isAssignment(), isBinaryOperation(), macveth::Node::setOutputInfo(), and toString().
getTypeFromStr()
static MVOpCode macveth::MVOp::getTypeFromStr (std::string S) inline static
Given a string it returns the type of function based on the MVOpCode it is defined for this compiler.
Definition at line 95 of file MVOps.h.
References macveth::AVG, macveth::CEIL, macveth::COS, macveth::EXP, macveth::FLOOR, GotoStartScop, macveth::MVOptions::IntrinsicsSVML, macveth::MAX, macveth::MIN, macveth::MVAssertSkip(), macveth::POW, macveth::ROUND, macveth::SIN, and macveth::UNDEF.
Referenced by MVOp().
isAddOrSub()
bool macveth::MVOp::isAddOrSub () inline
Check whether the operation is an addition or a substraction.
This is useful for reductions
Definition at line 190 of file MVOps.h.
References ClangOP.
isAssignment()
bool macveth::MVOp::isAssignment () inline
Shortcut to check whether a MVOp is of type BO_Assign.
Definition at line 179 of file MVOps.h.
References macveth::CLANG_BINOP, ClangOP, and getType().
Referenced by macveth::Node::setOutputInfo().
isBinaryOperation()
bool macveth::MVOp::isBinaryOperation () inline
Check whether the operation is binary or not.
An operation is binary if it is placed between two operands, in other case if is a function
Definition at line 186 of file MVOps.h.
References macveth::CLANG_BINOP, and getType().
toString()
std::string macveth::MVOp::toString () inline
Convert MVOp to string.
Definition at line 217 of file MVOps.h.
References macveth::CLANG_BINOP, ClangOP, getStrFromMVCode(), getType(), and MVOpC.
Referenced by macveth::Node::Node().
Member Data Documentation
@1
union { ... }
We can handle Clang BinOps or MVOps.
ClangOP
clang::BinaryOperator::Opcode macveth::MVOp::ClangOP
When CLANG_BINOP.
Definition at line 88 of file MVOps.h.
Referenced by getStrFromBinaryOperatorOpcode(), getTableMVOPstr(), isAddOrSub(), isAssignment(), MVOp(), and toString().
MVOpC
MVOpCode macveth::MVOp::MVOpC
When MVFUNC.
Definition at line 90 of file MVOps.h.
Referenced by getTableMVOPstr(), MVOp(), and toString().
Prefix
std::string macveth::MVOp::Prefix = ""
Prefix.
Definition at line 82 of file MVOps.h.
Referenced by getOpPrefix().
T
MVOpType macveth::MVOp::T
Type of the MVOp.
Definition at line 84 of file MVOps.h.
Referenced by getTableMVOPstr(), and getType().
The documentation for this struct was generated from the following file:
include/MVOps.h